### ISSUE TITLE
Remove Konenctivity feature gate and make it GA and enabled by default

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#10154]
Promote Konnectivity to GA, by removing Konenctivity feature gate and make it enabled by default for new clusters.
The OpenVPN option should remain available at cluster creation time as well as during cluster operation.

**Comment by rastislavs** [comment]
Postponing the last step (removing Konenctivity feature gate and making it enabled by default) until a later KKP release due to the upstream issues (mainly resource leaks).

**Comment by almereyda** [comment]
Could you share some information about these resource leaks?

I'm asking, because we have encountered a major breakdown of a cluster caused by a broken Konnectivity connection, that seemed close to impossible to repair. It is documented in https://github.com/kubermatic/kubermatic/discussions/10739 for informational purposes.

**Comment by rastislavs** [comment]
> Could you share some information about these resource leaks?

Konnectivity server may potentially run out of memory and be OOM killed, as described in https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/370
