### ISSUE TITLE
User cluster setup on vShpere with machine deployment nodes across multiple datacenter

### ISSUE THREAD

**Issue by archups** [kubermatic/kubermatic#10318]
### Description of the feature you would like to add / User story

As a end user (on behalf of customer),
I would like to have support for user cluster creation on vShpere with feasibility to setup machine deployment nodes across multiple datacenter
in order to distributed cluster setup for dynamic movement of pods based on resources availability and affinity set.

### Solution details

- Distributed user cluster setup support for vSphere.
- Allow user cluster creation span across multiple datacenters configured under vSphere Seed, instead of restricting to the selection of single datacenter.
- For each of user clusters, allow machine deployments creation across multiple datacenters configured under vSphere Seed.

**Comment by csengerszabo** [comment]
@archups this seems technically not possible for the first glance. We can put some efforts to dive deep and double check, but first, we need to. understand the setup where this would be needed and what problem they face with it, because it's possible that the approach should be tweaked, and there's a best practice for this issue.

**Comment by mfahlandt** [comment]
@archups this seems like an issue that could be solved in an architecure way with something like Service Mesh. I do not see the benefit of having a cluster run md in multiple dcs.
There are more risks than benefits if you have high latency or connection interrupts.
