### ISSUE TITLE
Investigate Constraint Cleanup

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#10471]
### What happened?

On dev, I can see this in the KKP API logs:

> {"level":"error","time":"2022-07-25T10:24:23.076Z","caller":"handler/routing.go:153","msg":"no matches for kind \"allowedregistry\" in version \"constraints.gatekeeper.sh/v1beta1\"","request":"/api/v2/projects/jgm2x2q9rc/clusters/ukrrflv4gw/constraints"}

Not sure where this is coming from. It's also weird that the Allowed Registry Controller does the same thing in its cleanup logic than in its reconciling logic: https://github.com/kubermatic/kubermatic/blob/master/pkg/ee/allowed-registry-controller/reconcile.go#L105-L113

### Expected behavior
Not quite sure.

### How to reproduce the issue?
No idea.

### How is your environment configured?

- KKP version: master
- Shared or separate master/seed clusters?: shared

**Comment by lsviben** [comment]
Got around to checking this. Its confusing but actually works fine.

The allowedRegistry reconciler basically gathers all AllowedRegistries, makes a list of the registries that they have and then creates/updates a default Constraint called `allowedregistry`.

So that is why the delete handling logic for the AllowedRegistries updates the registry list in the managed constraint.

And the log message that the KKP API server is getting is unrelated. This happens when clusters with OPA enabled are being created, and the UI is trying to get the Cluster Constraints before Gatekeeper starts up and creates the Constraint CRDs.

So IMO we can close this ticket
