### ISSUE TITLE
Test OIDC group support - viewer - Test Release 2.21

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#10541]
Test a simple flow of sharing project between user and group.

## Prerequisites:
- Google account in `kubermatic.com` domain
- Github account added to `internal` or `development` teams (kubermatic org)

## Test Procedure
1. Login to KKP using your google account.
2. Create a new project.
3. Create a small cluster inside the newly initialised project.
4. Go to members page of the new project, select groups tab and create a new group project binding with `viewers` role selected. (I suggest using `kubermatic:internal` or `kubermatic:development` group name)
5. Logout.
6. Login again, this time using your Github account. Shared project should be listed on Projects Overview page. Select it.
7. Verify that `Members` and `Service accounts` pages are not available to you.
8. On the `Clusters` page, verify that you **cannot** create a new cluster.
9. On the `Clusters` page, verify that you can see previously create cluster (step 3).

## Acceptance Criteria
Testing procedure is successful for all described test cases.

**Comment by hbernardo** [comment]
In general, everything worked fine.

I found a small issue only, after login with my Github account:
![image.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/d5337c59-2aae-4fe7-a6ec-7b783dbc356d)
Response from the request to `/api/v2/projects/kfpkp6fqn4/clusters/hfmbhm7qvr/applicationinstallations`: 
```
{"error":{"code":403,"message":"applicationinstallations.apps.kubermatic.k8c.io is forbidden: User \"hugofbernardo@gmail.com\" cannot list resource \"applicationinstallations\" in API group \"apps.kubermatic.k8c.io\" at the cluster scope"}}
```
Despite my Github user has the Kubermatic email assigned to it, the main email is my personal one, so I think that's why the error is happening as it's using my personal email instead of the Kubermatic one.

**Comment by hbernardo** [comment]
I retested it and the bug is gone after the fix.
