### ISSUE TITLE
Adding external Cluster from DigitalOcean Kubernetes platform fails

### ISSUE THREAD

**Issue by almereyda** [kubermatic/kubermatic#10676]
### What happened?

When adding the `kubeconfig` of an external cluster on DigitalOcean's Kubernetes platform, if only for viewing, an indistinguishable error is thrown to the UI, which when copied to the clipboard expands to:

```
cannot connect to the kubernetes cluster: failed to create restMapper: Get "https://3bff2cc3-d25a-4403-8ec2-27ff2db96690
.k8s.ondigitalocean.com/api?timeout=32s": getting credentials: exec: executable doctl not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

It is not clear which component of the KKP cluster controller is sending this message, nor how I could install `doctl` into that component.

### Expected behavior

The external cluster is added to the console, and its details can be viewed from there.

### How to reproduce the issue?

- Add a DigitalOcean Kubernetes kubeconfig to the KKP dashboard as an External Cluster.

### How is your environment configured?

- KKP version: v2.20.5-ce
- Shared or separate master/seed clusters?: Shared (ce ... https://github.com/kubermatic/docs/issues/1120)

### Provide your KKP manifest here (if applicable)

Not neccessary.

### What cloud provider are you running on?

DigitalOcean (KKP) + DigitalOcean Kubernetes

### What operating system are you running in your user cluster?

Ubuntu 20.04

**Comment by embik** [comment]
Hey @almereyda, thanks for your report. I'm not sure we can classify this as a bug, since it will not be possible to properly support Kubernetes providers that use arbitrary executables in their kubeconfig authentication flow. That's why this option to import existing clusters is generic. We should probably improve our documentation around this though.

To work around this, you can create a ServiceAccount and use its token in a kubeconfig again. That can be done via `kubermatic-installer convert-kubeconfig` for example (Seed clusters have the same limitation, so this helper should be usable for both scenarios).

**Comment by almereyda** [comment]
Good to know, thanks. I will try.

**Comment by almereyda** [comment]
The KKP cluster ceased, so I won't be able to try this again anytime soon.

Else let's note that DO also requires some secret juggling when setting up CCM and CSI:

- https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/getting-started.md#deployment
- https://github.com/digitalocean/csi-digitalocean#requirements

* https://github.com/kubermatic/kubermatic/issues/8847
* https://github.com/kubermatic/kubermatic/issues/10367
