### ISSUE TITLE
Allow the user to edit / extend the CoreDNS Corefile inside user cluster 

### ISSUE THREAD

**Issue by aryasalim91** [kubermatic/kubermatic#10804]
### Description of the feature you would like to add / User story

Allow the user to edit / extend the CoreDNS Corefile inside user cluster  

Requirement to implement dns rewrites inside coredns,
https://coredns.io/plugins/rewrite/
 but configmap gets overwritten after saves it.

### Additional information

KKP Version : 2.18
Kubernetes Version :  V1.22.4
OS Name and Version : Ubuntu 20.04
OS Kernel Version :  5.4.0-54-generic

**Comment by WeirdMachine** [comment]
It is possible to configure stub domains and upstream server when node-local-dns is enabled: https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/#stubdomains-and-upstream-server-configuration

This can be used to forward dns queries to an external dns server that applies the dns magic.

This is supported since KKP 2.19
