### ISSUE TITLE
kubermatic-installer convert-kubeconfig failing on gcp

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#11458]
### What happened?

Instead of creating a new service account with cluster-admin rights, the kubeconfig convertion is failing:
```
kubermatic-installer convert-kubeconfig ~/.kube/config -n kubermatic
INFO[0000] Converting cluster                            cluster=gke_poc-antos_us-central1-c_cluster-1 context=gke_poc-antos_us-central1-c_cluster-1
ERRO[0000] Invalid context, failed to reconcile: failed to create Kubernetes client: no Auth Provider found for name "gcp"  cluster=gke_poc-antos_us-central1-c_cluster-1 context=gke_poc-antos_us-central1-c_cluster-1
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: asdfasdf
    server: https://34.171.162.86/
  name: gke_poc-antos_us-central1-c_cluster-1
contexts:
- context:
    cluster: gke_poc-antos_us-central1-c_cluster-1
    user: gke_poc-antos_us-central1-c_cluster-1
  name: gke_poc-antos_us-central1-c_cluster-1
current-context: gke_poc-antos_us-central1-c_cluster-1
kind: Config
preferences: {}
users:
- name: gke_poc-antos_us-central1-c_cluster-1
  user:
    auth-provider:
      config:
        access-token: xxxx
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "2022-11-28T15:25:06Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

### Expected behavior

A working kubeconfig based on a service account instead of the authentication provider of google

### How to reproduce the issue?

1. create GKE cluster
2. use google cli to get kubeconfig
3.  execute `kubermatic-installer convert-kubeconfig ~/.kube/config`

### How is your environment configured?

- KKP version: `2.21.3`
- Shared or separate master/seed clusters?: `separate`

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by embik** [comment]
Upstream has [already deprecated auth plugins](https://github.com/kubernetes/kubernetes/pull/102181) that we could compile into `kubermatic-installer` and instead requires out-of-tree plugin binaries to be available. [Here's GCP's documentation on the change](https://cloud.google.com/kubernetes-engine/docs/deprecations/auth-plugin). As far as I understand, this requires the user environment to be properly set up.

I haven't verified if those plugins work with `kubermatic-installer` so we should do that, but it seems not a good idea to compile the deprecated plugins into `kubermatic-installer` since they're being removed with 1.26 (which will likely be in the next KKP release).

**Comment by xrstf** [comment]
Another option would be to shell out to `kubectl`.

Given how the command itself is currently kind of self-defeating (it is required for when you have a kubeconfig without static credentials, yet it cannot handle such a kubeconfig itself), I would like to get this fixed sooner than later.
