### ISSUE TITLE
Router-specific finalizers added to cluster resource even when router couldn't be created

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#11917]
### What happened?
User-reported issue:
KKP add finalizers before the resource is created for example:Router-specific finalizers added to cluster resource even when router couldn't be created.
https://github.com/kubermatic/kubermatic/blob/main/pkg/provider/cloud/openstack/provider.go#L253

### Expected behavior
Resource specific Finalizer should be added only after ensuring the resource creation.
 

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by xrstf** [comment]
> Resource specific Finalizer should be added only after ensuring the resource creation.

Nope, it's the other way around. Finalizers are always added first, because otherwise if adding the finalizer fails, we will forget that the resource has been created and this could leave to orphans. The cleanup logic tied to a finalizer needs to handle that the referred resource potentially doesn't exist [anymore].

**Comment by ahmedwaleedmalik** [comment]
> > Resource specific Finalizer should be added only after ensuring the resource creation.
> 
> It's the other way around. Finalizers are always added first, because otherwise if adding the finalizer fails, we will forget that the resource has been created and this could leave to orphans. The cleanup logic tied to a finalizer needs to handle that the referred resource potentially doesn't exist [anymore].

Agreed with @xrstf, not sure what the issue is here.

**Comment by embik** [comment]
I suspect that the problem is the OpenStack provider's cleanup logic. Looking at the code it seems that the scenario "finalizer was added, but router was never created" will prevent a cluster from deletion.

Router cleanup always runs when the finalizer is there upon cluster cleanup:

https://github.com/kubermatic/kubermatic/blob/5f48dc389029f90a9c2c3e9e5654add536b8b83e/pkg/provider/cloud/openstack/provider.go#L479-L485

And `deleteRouter` doesn't look like it's capable of handling the case where it doesn't actually need to delete a router:

https://github.com/kubermatic/kubermatic/blob/5f48dc389029f90a9c2c3e9e5654add536b8b83e/pkg/provider/cloud/openstack/helper.go#L347-L353

Unless gophercloud doesn't return an error when the resource to delete doesn't exist, but I couldn't find that in the docs on a quick scan.
