### ISSUE TITLE
MinIO chart in 2.23.0 fails to start on storage with existing data

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12430]
### What happened?

The MinIO chart we ship with KKP 2.23.0 upgrades its version to `RELEASE.2023-05-04T21-44-30Z` (#12241). Unfortunately, no check for breaking changes was conducted, or else we would have found [this banger](https://min.io/docs/minio/container/operations/install-deploy-manage/migrate-fs-gateway.html) - The "filesystem" mode is no longer supported.

This keeps MinIO as installed from the 2.23.0 charts from starting successfully with the following log:

```
ERROR Unable to use the drive /storage: Drive /storage: found backend type fs, expected xl or xl-single - to migrate to a supported backend visit https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html: Invalid arguments specified
```

This is **not** a problem for new installations, which seem to start just fine (e.g. on our `latest` snapshot environment which didn't have any data). This affects environments upgraded from 2.22 with existing etcd backups (or other data stored on this MinIO).

### Expected behavior

MinIO does not fail to start.

### How to reproduce the issue?

- Write data to MinIO installed in KKP 2.22.x.
- Upgrade KKP to 2.23.0 (including the MinIO chart).
- Observe MinIO pod failing to start.

### How is your environment configured?

- KKP version: v2.23.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

Perhaps we can downgrade, but we need to check what happens to existing (fresh) installations with this version when going from 2.23.0 to 2.23.1.

**Comment by embik** [comment]
TODO: Investigate if cleaning the volume with `rm -rf` is a workaround if you are not attached to your data.

**Comment by xrstf** [comment]
https://github.com/minio/minio/releases/tag/RELEASE.2022-10-29T06-21-33Z is the release that removes the filesystem stuff.

https://github.com/minio/minio/releases/tag/RELEASE.2022-10-24T18-35-07Z is therefore the most recent we can use without migrating.

**Comment by xrstf** [comment]
I suggest instead of downgrading we document this in the upgrade notes. The main issue is that when downgrading we run the risk of files suddenly "disappearing".

---

KKP 2.23 ships an updated version of Minio, which removed support for the legacy `fs` storage driver. Depending on the age of your Minio installation, you might need to perform a [migration](https://min.io/docs/minio/container/operations/install-deploy-manage/migrate-fs-gateway.html) to the new `xl` storage driver.

If you started with KKP 2.21+, the contained Minio version was already using the modern `xl` backend by default. Any older KKP release however shipped with an `fs` Minio version.

To verify what storage version your Minio is using, you can look at the `.minio.sys/format.json` file like so:

```bash
kubectl --namespace minio exec --container minio _minio_pod_here_ -- cat /storage/.minio.sys/format.json
```

The JSON file contains a `format` key. If the output looks like

```json
{"version":"1","format":"xl-single","id":"5dc676ac-92f3-4c19-81d0-2304b366293c","xl":{"version":"3","this":"888f699a-2f22-402a-9e49-2e0fc9abd5c5","sets":[["888f699a-2f22-402a-9e49-2e0fc9abd5c5"]],"distributionAlgo":"SIPMOD+PARITY"}}
```

you're good to go, no migration required. However if you receive

```json
{"version":"1","format":"fs","id":"baa787b5-43b6-4bcb-b1d7-acf46bcc0a05","fs":{"version":"2"}}
```

you must either

* migrate according to the [migration guide](https://min.io/docs/minio/container/operations/install-deploy-manage/migrate-fs-gateway.html), which effectively involves setting up a second Minio and copying each file over, or
* wipe your Minio's storage (e.g. by deleting the PVC), or
* pin the Minio version to the last version that supports `fs`, which is `RELEASE.2022-10-24T18-35-07Z`, using the Helm values file (set `minio.image.tag=RELEASE.2022-10-24T18-35-07Z`).

**Comment by embik** [comment]
Our decision for now: Implement a check in the installer to discover if the old backend is used and error if an upgrade is done that would break it. We want to revisit what to do with `fs` installations at a later point.

**Comment by csengerszabo** [comment]
Based on our latest discussion, we plan to include the migration logic into 2.24
