### ISSUE TITLE
KubeLB CCM integration - Test Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#12676]
__TBD__

Reference: https://github.com/kubermatic/kubermatic/pull/12667

**Comment by ahmedwaleedmalik** [comment]
I'll add in the description here after the corresponding PRs are merged.

**Comment by wozniakjan** [comment]
I gave it a quick try and so far stumbled upon these two rbac things, both for `ccm`
1) for the lease in tenant cluster
```
E1012 13:42:44.043167       1 leaderelection.go:336] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "kubermatic:kubelb-ccm" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```
I am curious if it's due to my suggestion https://github.com/kubermatic/kubermatic/pull/12667#discussion_r1343785186

2) for all sorts of things, including `LoadBalancer` in management cluster
```
E1012 14:31:14.617696       1 reflector.go:147] k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1alpha1.LoadBalancer: failed to list *v1alpha1.LoadBalancer: loadbalancers.kubelb.k8c.io is forbidden: User "system:serviceaccount:cluster-d527f8dcpq:kubelb-ccm" cannot list resource "loadbalancers" in API group "kubelb.k8c.io" in the namespace "cluster-d527f8dcpq"
```

I temporarily unblocked both to give the appropriate user cluster-admin. Last thing I stumbled upon was
```
2023-10-12T14:37:43.769Z        ERROR   Reconciler error        {"controller": "kubelb-ccm", "object": {"name":"lb-test-server","namespace":"default"}, "namespace": "default", "name": "lb-test-server", "reconcileID": "100fd088-d44c-487b-a12f-2610ffb08fd0", "error": "LoadBalancer.kubelb.k8c.io \"6bff7714-dd97-45ad-88f6-aa36eee3f87d\" is invalid: spec.endpoints[0].addresses[0].ip: Invalid value: \"\": spec.endpoints[0].addresses[0].ip in body should be at least 7 chars long"}
```
This was due to the fact that my tenant cluster had no public IPs for its nodes, resolved this manually by patching the deployment with additional arg `--node-address-type=InternalIP`. I suppose we may want to allow the configuration of this per tenant cluster.

Other than these minor things, it seems pretty solid.

**Comment by wozniakjan** [comment]
one more detail I stumbled upon today - https://github.com/kubermatic/kubermatic/pull/12721

**Comment by wozniakjan** [comment]
one more tiny nit, the status condition was imho incorrect - https://github.com/kubermatic/kubermatic/pull/12725

**Comment by wozniakjan** [comment]
with https://github.com/kubermatic/kubermatic/pull/12785 fixed, I was able to test the integration end-to-end (in dev for now until qa is updated), I tried in kubevirt (with InternalIP) and gcp (with ExternalIP). Both look good to me and I didn't discover any new and unknown issues.

**Comment by ahmedwaleedmalik** [comment]
@wozniakjan I think we can close this one now. WDYT?
