### ISSUE TITLE
Define backup/restore strategy for seed-clusters

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1271]
Define a strategy on how to backup & restore the seed-cluster.
Should we:
- Only backup the etcd?
- Only backup the relevant manifests?
  - What are relevant?
- How do we restore?

Should we use Ark?

This issue is just about definition on what would be the best way.
Create follow-up issues after we have a definition.

**Comment by pkavajin** [comment]
Timebox: 2x 4h -> 8h

**Comment by pkavajin** [comment]
@xrstf please talk with henrik about this one and define the requirements.

**Comment by xrstf** [comment]
Henrik's preliminary specs are as follows:

* We want backups to defend against hardware/infrastructure failures, as in deleted disks or data corruption.
* Allowed restore times are dependent on the customer. Our primary goal is to enable them to make backups in the first place, so they can, if shit hits the fan, do a restore.
* After a backup restore, all user clusters on a given seed should be functioning again.
* It's acceptable to have manual actions during the restore, like DNS changes or restarting pods.

**Comment by xrstf** [comment]
Performing manual etcd snapshots guarantees consistency, but also ties us to the Kubernetes version. Hence backups cannot easily be used to migrate between Kubernetes versions.

Ark however works on CRD basis and basically gives us a tar.gz file with a bunch of YAML files (one for each resource) in them. But Ark backups are [not atomar and can be inconsistent](https://heptio.github.io/ark/v0.9.0/about).

**Comment by xrstf** [comment]
Henrik said that atomic backups are not really required, so I think we could go with Ark:

* User clusters are already backed up by our Backup Controller, which performs regular (every 20 minutes by default) etcd snapshots and uploads those to the seed's minio service. Afterwards it removes all but the last N (by default N=20) backups for that cluster.
* User clusters do not have any other state we are interested in. Prometheus is ephemeral and we can easily afford losing its metrics in case of a restore.
* The seed cluster should have Ark deployed in whatever namespace. This means setting up the CRDs for Ark and the secrets for accessing the final backup storage.
* Ark should perform the etcd backup and also back up all volumes on the seed. This will include the minio volume, so each seed backup will automatically contain all the user cluster backups.
* Ark's Kubernetes controller itself does not do backups, but instead Ark uses a client that interacts with the controller by creating resources (see [Ark docs](https://heptio.github.io/ark/v0.9.0/about)). This means we need to create a custom CronJob on the seed that uses some Docker image with Ark inside and trigger that once every X minutes.

I propose we create a Helm chart at `config/backup/ark` that contains Ark's CRDs, our secrets and the CronJob definition.

**Comment by xrstf** [comment]
Ark natively supports only AWS, GCP and Azure as platforms where it can create snapshots from volumes. Since Kubermatic supports more cloud providers we need to extend Ark. There are two options:

1. Writing custom plugins for Ark for every cloud provider we support. That could get tedious, but would provide possibly better performance than option 2, but if one of our cloud providers has no snapshot API, we're out of luck and need to fallback to a file-based backup anyway.
2. Use Ark's native restic integration. Restic copies volumes file-by-file and thereby supports pretty much any volume provider.

Henrik suggested trying out restic and from my experiments on the dev seed cluster, this is what I found:

* To use restic, you have to annotate your pods and tell restic which volumes should be backed up.
* Performance is like 500 MB/min (restic performs encryption and deduplication). Subsequent backups are usually faster because less data needs to be transferred.
* To provide proper atomic snapshots, we will need to integrate with each software that we want to backup (i.e. Elasticsearch, Prometheus, ...). This is something we need to do anyway because even when using AWS' native volume snapshots we need to trigger flushes/fsyncs to make sure that the data in the volumes is complete. This integration can be performed by using a hook (defined as another annotation on the pods, defining a shell command), like running `etcdctl snapshot` before restic copies the files.
* In some cases we will need additional backup volumes, like for Prometheus. Restic only every backs up a full volume. Software like Prometheus create their own snapshot inside their data directory, so we would need to define a hook like `sh -c "prometheus make-snapshot-now-please && rm -rf /backupvolume/* && cp -ar /prometheus/data/snapshot /backupvoume"`
* Restores will be slightly more involved because in some cases you cannot simply take the backed up files and start the software from it, but you have to manually import it back (think of a SQL dump that needs to be imported before you can use the database again).

I think we can settle on this and create further stories:

* implement ark/restic Helm charts
* integrate backups into (seed-)Prometheus
* integrate backups into Elasticsearch
* integrate backups into ...

@mrIncompetent Yay or nay?

**Comment by mrIncompetent** [comment]
Yay!
