### ISSUE TITLE
Conflicting API types when installing on Rancher Kubernetes cluster

### ISSUE THREAD

**Issue by bassemtadros** [kubermatic/kubermatic#12906]
### What happened?

Trying to add static users to dex or integrate it with keycloak, the new users can login to kkp but it appears to be missing permissions, 

Note that the seed is based rancher kubernetes cluster.

here is a sample of the missing permissions errors  

{"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-lfjdc\" is forbidden: User \"bassem@example.com\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get clusters.kubermatic.k8c.io zfj275dzlw)

{"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-lfjdc\" is forbidden: User \"bassem@example.com\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get clusters.kubermatic.k8c.io zfj275dzlw)

Can not see clusters the project or create new clusters.

### Expected behavior

that the new users created be able to see and create clusters once given access

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by embik** [comment]
It appears that rancher API types (in particular `clusters.management.cattle.io`) are interfering with KKP, likely because they share the same short-form `clusters`.

I don't know enough about Rancher to judge if those API types would be necessary on a seed cluster provisioned by Rancher, so this would need further investigation. It's particularly interesting that controller-runtime seems to be confused about which API type on the cluster side to use for our typed API. I've never seen this before.

**Comment by embik** [comment]
The "quick" fix / recommendation for this is to ensure that no unused API types are installed on the seed cluster prior to deploying KKP.

**Comment by bassemtadros** [comment]
yes correct, the name in the CRDs are the same, unfortunately i can not delete clusters.management.cattle.io as this will break the rancher cluster.
I guess you will have the same behavior with any cluster management tool handling the seed. 

any ideas?

**Comment by embik** [comment]
> I guess you will have the same behavior with any cluster management tool handling the seed.

I would disagree with that because most cluster management tools (e.g. KKP itself) will not install "cluster management" type APIs into clusters created by them. I can't speak about Rancher due to lack of knowledge, but it seems that either it is installing API types that shouldn't be in managed clusters, or you are trying to install KKP alongside Rancher on the same cluster, which I would advise against.

> any ideas?

For right now, the only suggestion I have is to create the seed cluster with a different tool (e.g. [KubeOne](https://github.com/kubermatic/kubeone) or plain `kubeadm`). We would need to investigate why the controller-runtime client discovers the wrong API type for our APIs.
