### ISSUE TITLE
Migration from machine-controller to OSM

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13402]
Follow up for https://github.com/kubermatic/kubermatic/pull/13381

Creating an issue so that we don't forget. More details will be in the PR.
/assign
/milestone KKP 2.26

**Comment by csengerszabo** [comment]
According to @ahmedwaleedmalik, the migration should cover these in the Installer or other components:

1. List all clusters that have OSM explicitly disabled
2. Edit all MDs and add the `k8c.io/operating-system-profile: osp-$OS_NAME”`
3. Documentation + release notes

**Comment by csengerszabo** [comment]
Output from SIG-Cluster-Management meeting:

There are concerns having it in the installer, and instead it should be ran in the controller code, because not all customers use the installer.

We need to prevent nodes to be rotated at the same time, so that we have to slow down the rollout of the migration, and define a new label that the cluster admin has to put on to these clusters, which is a manual step shown in the upgrade notes.

**Comment by ahmedwaleedmalik** [comment]
> We need to prevent nodes to be rotated at the same time, so that we have to slow down the rollout of the migration, and define a new label that the cluster admin has to put on to these clusters, which is a manual step shown in the upgrade notes.

1. What is the other way we support installing KKP without an installer?
2. The label doesn't rotate the machines/nodes by itself; it will only ensure that OSM can process and generate configs against this machine deployment. To rotate the machines you'll have to follow https://docs.kubermatic.com/operatingsystemmanager/cheat-sheets/rollout-machinedeployment/

**Comment by csengerszabo** [comment]
> According to @ahmedwaleedmalik, the migration should cover these in the Installer or other components:
> 
> 1. List all clusters that have OSM explicitly disabled
> 2. Edit all MDs and add the `k8c.io/operating-system-profile: osp-$OS_NAME”`
> 3. Documentation + release notes

This is still the final approach in the end.
