### ISSUE TITLE
Test APIServerAllowedIPRanges with seed cluster PodCIDR - Test Release 2.26

### ISSUE THREAD

**Issue by cnvergence** [kubermatic/kubermatic#13772]
KKP 2.26 test ticket for the https://github.com/kubermatic/kubermatic/pull/13579

Steps:
1. Create a user cluster on a KKP setup with expose strategy LoadBalancer
2. Restrict an access to the API server following https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/networking/apiserver-policies/#api-server-allowed-source-ip-ranges
3. Ensure that seed cluster Pod CIDR was added to the `front-loadbalancer` service in the annotation `service.beta.kubernetes.io/load-balancer-source-ranges`

**Comment by akash-gautam** [comment]
Currently on creating user cluster with expose strategy LoadBalancer (without specifying any allowed IP ranges for api server) on QA the nodes aren't able to join the cluster, tried with AWS & Vsphere.

**Comment by akash-gautam** [comment]
User cluster creation with expose strategy LoadBalancer worked after adding the below config under `nodeportProxy` in the seed spec.
```
    envoy:
      dockerRepository: docker.io/envoyproxy/envoy-distroless
```

**Comment by akash-gautam** [comment]
The changes **do not** work on QA which I think is because we are trying to get the seed's pod cidr from the node spec (https://github.com/kubermatic/kubermatic/blob/v2.26.0-rc.0/pkg/resources/data.go#L902) but on the QA seed nodes this field is not available, we have only the `providerID` in the node spec.

![Image](https://github.com/user-attachments/assets/b2014a29-d0e6-4667-ad66-ba4a321814b1)

This will work on a kubeone based seed I believe as the `podCIDR` available in node spec but may or maynot work for non kubeone seed, I can test if any environment with k1 seed and KKP v2.26.0-rc.x is available.

We can include this in the release & mention the limitation in the doc or hold it & look for other alernatives for getting the seed's pod cidr which will work regardless of how the seed is set up, the product/release team can take a call on this cc @csengerszabo @xrstf

**Comment by xrstf** [comment]
cc @cnvergence https://github.com/kubermatic/kubermatic/pull/13579 introduced GetPodCIDR()

**Comment by cnvergence** [comment]
Thanks for catching this, should we revert this one and get back to further investigation on how to automate adding this IP range?

**Comment by xrstf** [comment]
@cnvergence ping we're getting close to release date and need to know what to do here. :)

**Comment by xrstf** [comment]
Okay, I have made the decision: We are reverting this PR. I did not get proper feedback on which cloud providers this was ever shown to work and so have to assume it never worked anywhere.
