### ISSUE TITLE
Discuss and possibly implement `controller` label for error metrics

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1627]
Currently we have one global error metric for all controllers. There were some voices preferring to have them distinct per controller, e.G. by adding a label.

*Acceptance criteria:*

* A decision was made whether we want to add the originating controller to the error metrics
* If we decided to do so, a label for the originating controller was added

**Comment by mrIncompetent** [comment]
One of the things to keep in mind here, to have (a) effective metric(s) in that topic, the usage `runtime.HandleErr` must be completely removed as `runtime.HandleErr` cannot be scoped.

I'm definitely in favor of giving each controller a own error-metric, but i'm not entirely sure if that's easy to implement due to our big usage of `runtime.HandleErr`

**Comment by mrIncompetent** [comment]
With the migration to the controller-runtime, we now have a dedicated error metric per controller
