### ISSUE TITLE
Progress indicator while cluster creation

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#2237]
**User Story**
When clicking on `Create` in the wizard we currently just wait until the cluster is 'ready' to display. This might take some time and the UI doesn't send any feedback. 
To improve the user experience it might be a good idea to display some more informations about the current creation status within a progress indicator. Maybe the backend could provide some more informations while creating a cluster.
WDYT @p0lyn0mial @maciaszczykm @mrIncompetent ?

**Comment by maciaszczykm** [comment]
Yeah, I agree on that. It is important to let users know that something is going on in the background since this can take a while. We can start with some indeterminate indicator (i.e spinner overshadowing wizard card) because I don't know if backend will be able to provide such specific progress info to use determinate one. Perhaps at least some steps if there are any?

Some progress bars and spinners from Angular Material:
https://material.angular.io/components/progress-bar/overview
https://material.angular.io/components/progress-spinner/overview

**Comment by p0lyn0mial** [comment]
I also like the idea, can be challenging to implement on the backend side but not impossible :) I'm fine with having a spinner for the time being.

**Comment by mrIncompetent** [comment]
We could go really fancy by using a Socket & Sending a summary of the Deployment + StatefulSet conditions :P

**Comment by toschneck** [comment]
:+1: for this. currently it's also not ideal that we show the components as `failed`.

**Comment by p0lyn0mial** [comment]
It would be easier to implement a progress bar that doesn't tell you how far you are in the process. We would have to change/prepare the API. Simply displaying a progress bar sounds like a good start.
