### ISSUE TITLE
Adjust the userClusterConnectionProvider interface to only provide a dynamic client

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2343]
**User Story**

As a developer I want to avoid any unecesary code. Currently we have a lot of `Get${MYTPE}Client` funcs that return a typed client. We could avoid all of that if we used a [dynamic client](https://github.com/kubernetes/client-go/tree/master/dynamic)

**Acceptance criteria**

* All the existing `Get${MYTPE}Client` funcs do not exist
* The `userClusterConnectionProvider` interface has exactly one method: `GetClient`

**Comment by nikhita** [comment]
I'd like to work on this. :)

**Comment by nikhita** [comment]
Btw we can also use [dynamic informers](https://github.com/kubernetes/client-go/tree/master/dynamic/dynamicinformer) and [dynamic listers](https://github.com/kubernetes/client-go/tree/master/dynamic/dynamiclister) later (added by @p0lyn0mial upstream :tada:).

These will be present in the latest release i.e. 1.13 - which hasn't released yet.

**Comment by nikhita** [comment]
Quick update here: I started working on this using the [controller-runtime client](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go). This is the client that kube-builder uses. This client uses _both_ the dynamic client and the typed client. It takes a `runtime.Object` and performs CRUD operations on it.

Differences between the [client-go dynamic client](https://github.com/kubernetes/client-go/tree/master/dynamic) and the [controller-runtime client](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go):

- The client-go dynamic client performs CRUD on `unstructured.Unstructured` objects. This means for each operation we need to convert `data` -> `unstructured.Unstructured` -> `data`. There is no data loss that occurs but it just cumbersome.
- The controller-runtime client uses both the dynamic client and the typed (generated) client. It performs CRUD on `runtime.Object` objects. So it first checks if the object is of the `unstructured.Unstructured` type. If yes, it uses the dynamic client. If no, it uses the typed client. In this method, we won't have to conversions but we _will_ have to use type casting to convert the `runtime.Object` back into the type of the object we want, say `*corev1.Node`.

If we want to use "generic" clients, there is no way to win around this without using either conversions or casting (golang generics, anyone? :wink: ). The second method seems better because casting is easier than conversion each time.

I also spoke with the upstream client-go folks about this idea but most didn't see any added advantage since we still need an extra step anyway (makes sense). Also, this other client is in kubernetes-sigs so if anyone wanted casting rather than conversion, they can just use this. ¯\\\_(ツ)\_/¯

But moving to this client is currently blocked on #2354 . I have just added the client to vendor manually to unblock myself but I'll send a proper fix when #2354 gets merged.

**Comment by alvaroaleman** [comment]
> The controller-runtime client uses both the dynamic client and the typed (generated) client. It performs CRUD on runtime.Object objects. So it first checks if the object is of the unstructured.Unstructured type. If yes, it uses the dynamic client. If no, it uses the typed client. In this method, we won't have to conversions but we will have to use type casting to convert the runtime.Object back into the type of the object we want, say *corev1.Node.

Are you sure about the casting? In the Zevenet LB controller I did something like this:

```
// Fetch the Service instance
service := &corev1.Service{}
err := r.Get(ctx, request.NamespacedName, service)
```

Maybe it does the casting behind the scenes? I as a user didn't have to do any of it

**Comment by kdomanski** [comment]
Estimated as 8

**Comment by nikhita** [comment]
> The userClusterConnectionProvider interface has exactly one method: GetClient

This is still outstanding.
