### ISSUE TITLE
Improve initial node deployment creation

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#2928]
**User Story** 
At the moment when the user is creating a cluster, there are separate requests to create the cluster and to create initial node deployment. Request to create initial node deployment is send from the UI after the user is redirected to the cluster details page and the cluster is healthy. In the meantime, initial node data is stored in the local storage. This causes potential issues, i.e. when the user closes the browser before initial node deployment creation or if the local storage is corrupted/removed.

To improve the situation we can start with changes in the API. We can wait for a cluster to be created in the initial request and create initial node deployment. It shouldn't take too long but it should fix most of the problems.

The target solution for this issue seems to be implementation of a new controller that will handle initial node deployment creation and will store machine deployments/some other CRDs in the seed cluster as a cache/queue and when the clusters will be ready then the controller can add machine deployments into the clusters.

**Acceptance criteria**
- [x] API should handle the creation of initial node deployments.
- [x] There should be a metric and alert for cases where creation will fail after a certain timeout.
- [ ] There should be tests to cover the changes in the API.
- [ ] UI should be adjusted and tested as well.

cc @mrIncompetent @alvaroaleman @kgroschoff @p0lyn0mial @thetechnick   

Feel free to edit this issue if you feel that description could be changed.

**Comment by p0lyn0mial** [comment]
@maciaszczykm please check if the same doesn't apply to ssh keys, e.g. adding an ssh key to a new cluster.

**Comment by multi-io** [comment]
FYI we're currently adding a new CRD `MachineDeploymentRequest` to the seed cluster (namespaced, created in the cluster-xxxx namespace), which will for now just contain the MachineDeploymentSpec of the MachineDeployment to be created in the user cluster. The controller is the next step. We'd then also refactor the cluster creation api endpoint so it'll only create this resource rather than trying to create the MD itself in a background goroutine.

Would you be interested in this?

Eventually we'd also like to use this for creating machinedeployments in a different cloud/region than the cluster's original one (connected via a WireGuard/kilo based VPN most likely) -- in that case the cloud controller (or some other controller) may have to create a network/subnet for the machinedeployment, similarly to how the cluster controller currently [does it](https://github.com/kubermatic/kubermatic/blob/3d34260b98ce214630899d6e26fd8bd78d9a793c/api/pkg/provider/cloud/openstack/provider.go#L181) for a new cluster on openstack.

**Comment by multi-io** [comment]
> We'd then also refactor the cluster creation api endpoint so it'll only create this resource rather than trying to create the MD itself in a background goroutine.

Thought about this again -- I guess this wouldn't really solve the problem because you'd still have two separate POST requests against the seed cluster api -- one to create the cluster resource, and then another one to create the MachineDeploymentRequest (and the latter couldn't even happen immediately because the cluster-xxx namespace is created asynchronously by the cluster controller). So there would still be a time window in which the apiserver might be restarted and the node deployment forgotten.

So coming to think of it, the only viable solution might be to write the initial node deployment into the cluster resource somehow, possibly serialized into an annotation, and then the cluster controller would create the MachineDeployment from that (and delete the annotation).

We'll still pursue the `MachineDeploymentRequest` thing because we need it for our multi-region cluster setups though.

**Comment by maciaszczykm** [comment]
Reopen to discuss.

**Comment by maciaszczykm** [comment]
@multi-io This sounds somewhat similar to the thing that we discussed internally not a long ago. Currently, we have a bit too much of action in one endpoint and splitting it is very good idea. Especially because right now if the API would crash all the loops that were running in the background would disappear. This can cause missing initial deployments from time to time as you noticed. Can you share the status of your work? Perhaps let's setup a meeting and discuss how we can cooperate to get it done.

cc @kubermatic/ui-team

**Comment by maciaszczykm** [comment]
We would also be interested in having a possibility to create addons not only from the cluster details view but also from the wizard. This means we can possibly use similar solution to handle this too.

**Comment by maciaszczykm** [comment]
cc @zreigz @floreks @lsviben 

We should talk about this at some point and do some improvements here.

**Comment by maciaszczykm** [comment]
The API part is ready in https://github.com/kubermatic/kubermatic/pull/6064. Can the lifecycle team take care of the rest? Please feel free to reuse the code in your pull request or just modify existing one. 

/label team/lifecycle
