### ISSUE TITLE
Update run.kubermatic.io to 2.10

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3382]
**User Story**

**Acceptance criteria**

* Kubermatic 2.10 is deployed via CI from the release/v2.10 branch to run.kubermatic.io

**Comment by toschneck** [comment]
One information on this. @scheeles talked to me that we should reinstall run.kubermatic.io like follow:
- kubeone on GKE as master/seed
- nightly reapply of kubermatic `master` branch, so that we can demo on the latest development changes, but will be more stable then cloud.

@alvaroaleman If this issue is more about testing the upgrade, we can also create a separate ticket for the reinstallation based on kubeone

**Comment by alvaroaleman** [comment]
We'll do that after the Openshift integration and offline support is done

**Comment by toschneck** [comment]
@alvaroaleman fine for me, maybe someone of PS can also set this up in future, so no time pressure here.
