### ISSUE TITLE
Make addon-controller ignore clusters with deletion timestamp

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#3488]
**User Story**
Currently when cluster is being deleted addons-controller constantly recreated resources back and cloud resources that was created from addons end up orphaned (LBs/PVs).

**Comment by alvaroaleman** [comment]
Hm, thinking about this again we should probably just make the addon-controller ignore clusters with a deletion timestamp. If we actively delete the addons, the addon-controller will potentially delete LoadBalancers on whose deletion we dont wait in the kubernetes/openshift controller because we don't know about their existance, leading to stale resources
