### ISSUE TITLE
Implementation of OpenAPI for the api server

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#366]
The benefits we want to achieve which this issue:
- generate documentation for the api
- generate api libraries (golang, javascript, python)

**Comment by andriisoldatenko** [comment]
Notes of some research regarding swagger/OpenAPI:
After reading [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification) and brief history of swagger I found 2 different tools written in Java and Golang:
- [swagger-codegen](https://github.com/swagger-api/swagger-codegen) contains a template-driven engine to generate documentation, API clients and server stubs in different languages by parsing your OpenAPI / Swagger definition.
- [go-swagger](https://github.com/go-swagger/go-swagger) - written in Golang some notes from README.md
>Why is this not done in the swagger-codegen project? Because:
>* I don't really know java very well and so I'd be learning both java and the object model of the 
> codegen which was in heavy flux as opposed to doing go and I really wanted to go experience of designing a large codebase with it.
> * Go's super limited type system makes it so that it doesn't fit well in the model of swagger-codegen
> * Go's idea of polymorphism doesn't reconcile very well with a solution designed for languages that actually have inheritance and so forth.
> * For supporting types like [][][]map[string][][]int64 I don't think it's possible with mustache
> * I gravely underestimated the amount of work that would be involved in making something useful out of it.
> * My personal mission: I want the jvm to go away, it was great way back when now it's just silly (vm in container on vm in vm in container)

I prefer Go version, because it's easy to setup (we already have Go in production) no need to run Java.

## Main plan of works looks like:
- Add comments to your API source code
```
// @APIVersion 1.0.0
// @APITitle My Cool API
// @APIDescription My API usually works as expected.
// @Contact api@contact.me
// @TermsOfServiceUrl http://google.com/
// @License BSD
// @LicenseUrl http://opensource.org/licenses/BSD-2-Clause
// @BasePath http://host:port/api/
```
- Generate documentation as JSON/YAML according to the Swagger Spec/OpenAPI spec;
- Displays api docs using Swagger UI (for me looks most clear, but we can use alternatives).
- Run the Swagger generator.

TBD

## Related PRs:
- https://github.com/kubermatic/api/tree/feature/open-api-for-the-api-server

**Comment by scheeles** [comment]
LGTM

We should use go-swagger. Mostly everyone is familiar with go at Loodse

**Comment by guusvw** [comment]
LGTM :+1:

**Comment by andriisoldatenko** [comment]
WIP https://github.com/kubermatic/api/pull/376

**Comment by andriisoldatenko** [comment]
![image](https://user-images.githubusercontent.com/1374633/29263936-57117a1e-80db-11e7-915e-16dc5705c6b4.png)
