### ISSUE TITLE
Configure ExposeStrategy per SeedCluster

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubermatic#4721]
**User Story**
As a customer running Kubermatic on prem in vSphere, I am using MetalLB with `exposeStrategy: LoadBalancer`
https://docs.kubermatic.io/concepts/expose-strategy/expose_strategy/

This works fine for my on-prem workload, because it allows my firewalling team to have fixed port allocations, for a fixed subnet of IP addresses.

But now I want to add a new Seed Cluster on a cloud provider to my Kubermatic Installation and I would like to use the `NodePortProxy` expose strategy for this new seed cluster, so I don't have lot's of expensive LoadBalancers.

**Acceptance criteria**
- [ ] `exposeStrategy` can be configured on seed cluster level (or even finer)

**Comment by alvaroaleman** [comment]
@thetechnick this is already set per seed: https://docs.kubermatic.io/kubermatic/v2.12/concepts/expose-strategy/expose_strategy/

Its done indirectly as an arg on the controller manager, because as long as we support `datacenters.yaml` we can not make it a property on the `seed` crd, because then it can only by used when using the `seed` crd.

Closing for now, please feel free to re-open if I misunderstood anything.

**Comment by thetechnick** [comment]
In Kubermatic `v2.12` the expose strategy is set only on the API server and thus global to the Kubermatic installation:
https://github.com/kubermatic/kubermatic-installer/blob/527433fb626d79c4baa1eec44134ee43d2c64e69/charts/kubermatic/templates/kubermatic-api-dep.yaml#L67

There are also no instructions in the docs to change the expose strategy only on a single seed cluster.

If this feature already exist, we still have to make it available to users and PS, by providing docs and add the option to our installer.
