### ISSUE TITLE
Addon reconciling errors during OpenShift cluster creation

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#4881]
**User Story**

Errors during cluster creation:
![Screenshot 2019-12-16 at 12.37.38.png](https://images.zenhubusercontent.com/5cf547a42356dd3bc0e53bb8/d1658147-9f40-4d12-b42c-3191b7b24d27)

Eventually the cluster is created successfully and working.

**Acceptance criteria**

Cluster should be created without reconciling errors

**Comment by alvaroaleman** [comment]
Yeah, to solve this we need to introduce ordering and state into addons, so the "CRD" addon is deployed successfully before the other ones are.

**Comment by alvaroaleman** [comment]
> Yeah, to solve this we need to introduce ordering and state into addons, so the "CRD" addon is deployed successfully before the other ones are.

I decided to not do it like that and instead allow addons to specify their required resource types (can be a CRD or an apiservice). The reason is that if we allow dependencies for addons, we have to respect the dependency graph for cleanup as well, and I do not think adding that to our API is a good idea.
