### ISSUE TITLE
presets can be used in DCs/regions for which they don't work

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#4937]
**User Story**
Sales ran into an issue, where they attempted to use an AWS preset in a region, but the preset specified VPC/subnet that were only present in another reason. Please design a clean way to make this impossible and update this ticket.

**Comment by toschneck** [comment]
Maybe it make sense to make presets in general dependent to a datacenter configuration. E.g if we would have different vSphere datacenters we could also have different networks what are only valid in one datacenter. So we may have a tree like:
```
Datacenter AWS - Frankfurt
  |--- preset-frankfurt-a
  |--- preset-frankfurt-b
Datacenter AWS - Dublin
  |--- preset-dublin
Datacenter vsphere - Loodse
  |--- preset-vsphere-loodse-net
Datacenter vsphere - hetzner
  |--- preset-vsphere-hetzner-net
```

**Comment by zreigz** [comment]
Yes, I see. Currently, I can not change the preset structure because we have CRD (migration, compatibility). I can easily extend the preset cloud provider structure for the datacenter field. We will filter out presets for the specific datacenter. Right now we can specify multiple preset objects. I can add new fields and extend the API to filter it out. This approach was agreed for the future extension.
```
Preset: A
  - AWS
    - Datacenter: A
Preset: B
 - AWS
   - Datacenter: B
```
