### ISSUE TITLE
Tunneling Expose Strategy Alpha Stage

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#4942]
**User Story**
We're running into a limit of 25 AWS clusters caused by the fact, that there can only be 2 listeners on an AWS LB, and we're using 2 listeners per cluster.

https://loodse.slack.com/archives/CC3BRUSJH/p1573035498034900

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/4942).

**Comment by irozzo-1A** [comment]
@kdomanski If my understanding is good this issue should be described this way:

When running a seed cluster in AWS with [global load-balancer](https://docs.loodse.com/kubermatic/v2.13/concepts/expose-strategy/expose_strategy/#global-loadbalancer) expose strategy we use 2 listeners for each user cluster.

- one for the apiserver
- the other for the openvpn server

The reason is that currently we cannot use SNI for the apiserver due to https://github.com/kubernetes/enhancements/pull/1216, so the loadbalancing is handled the following way.

A service of type loadbalancer is created for an envoyproxy deployment. For each service/user-cluster the [lb-updater](https://github.com/kubermatic/kubermatic/tree/master/api/cmd/nodeport-proxy/lb-updater) is adding a port pointing to an envoy cluster that is configured dynamically by a [sidecar container](https://github.com/kubermatic/kubermatic/tree/master/api/cmd/nodeport-proxy/envoy-manager) running on each envoyproxy pod. This on AWS triggers the creation of a new listener.

**Comment by irozzo-1A** [comment]
@youssefazrak have you something to amend/add with respect to my comment?

**Comment by youssefazrak** [comment]
@irozzo-1A Nothing to add, that's well summarized.

Now the question is how we could overcome this:
- Raise the quota for the ELB (Easiest way **IF** accepted). 
- Use multiple ELBs. Not cost-effective.
- Find a way to LB the packets without using SNI. This would mean TLS termination at an LB or Ingress level. Also, apiserver traffic is not the same as OpenVPN traffic (by default udp 1194, can use TLS 443 for example) and other specific things related to the type of traffic and headers that we are able to play with needs to be taken into account.

**Comment by irozzo-1A** [comment]
> * Raise the quota for the ELB (Easiest way **IF** accepted).

This is my preferred one, simple and effective ;-) https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-limits.html

If a customer has much higher needs can still consider the option of using the nodeport, and if he can afford the cost the lb per user cluster. It does not seem to be a blocker.

IMHO Trying to find a middle ground between 1 global lb and 1 lb per user-cluster is complicated, adds another level of loadbalancing and does not bring much value.

**Comment by youssefazrak** [comment]
One other solution possible at this point due to the limitation on AWS (number of listeners, no port ranges available, so 1:1 mapping between the listener and one specific port) is to use EIP(s).

We would have to implement the following assuming we use multiple public IPs for redundancy:

- DNS load balancing: multiple A records pointing to the EIPs. 
- This traffic will be forwarded directly to the seed cluster nodes. Each cluster-ns is exposing the OpenVPN and apiserver services as NodePort svc. This means that whichever node receiving the traffic from the EIPs will be able to send it to the correct pods on the same node or different node.
- In order to avoid a scenario where a node is down and the EIP forwarding traffic to the node (no health check feature), a controller will need to be deployed on the seed cluster: It will check the health of the nodes and manage the association/disassociation of the EIPs to the nodes.

**Comment by irozzo-1A** [comment]
> * DNS load balancing: multiple A records pointing to the EIPs.

This implies that we need to assign one EIP to each usercluster to be used for the kubernetes service in the default namespace (to reach out the apiserver from the user cluster) as we cannot use a dns name there.

So each user cluster will have one and one only node as entrypoint. This should be acceptable as the controller will handle the failover and we can probably accept some small outages.

**Comment by irozzo-1A** [comment]
@kdomanski https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#choosing-your-notification-settings

**Comment by xrstf** [comment]
@shaase-ctrl Should we recreate this epic maybe?
