### ISSUE TITLE
Improve AddOn Image Management

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#5153]
**User Story**
If a customer currently wants to add their own add-ons to kubermatic, they need to extend our versioned add-on image and then add their own add-on content. This works, but on every Kubermatic version update they need to rebuild/push/update config with a new custom image-tag. If they don't update it, an old (potential unfixed) version of the default add-ons get deployed. 

This behavior could get improved, if we use a separate customer addon image without dependency to Kubermatic default add-ons. The target should be that we can release Kubermatic add-ons and customer specific add-ons independently.

**Acceptance criteria**
- Customer add-on's (default or selectable) could be managed by an independent docker image
- A Kubermatic update doesn't enforce to rebuild the customer add-on's
- The Kubermatic add-ons (could still be overwritten but independent of the customer add-ons

**Comment by xrstf** [comment]
> If they don't update it, an old (potential unfixed) version of the default add-ons get deployed.

This is precisely why we *force* users to at least re-tag their addons Docker image, so they do not accidentally unknowingly ship outdated addon manifests. That is why in #6102 we made it so that users can only ever supply a _suffix_ for the Docker image tag and are therefore forced to act when updating. Without doing this, the KKP components won't even come up and that's a very good signal to the user that they forgot something.

**Comment by toschneck** [comment]
agree on christoph comment, but the point to split up the default and accessible addons is still valid

**Comment by rastislavs** [comment]
Apart from splitting the default and accessible addons, it would make sense to allow specifying the manifest source per accessible addon, in the Addon Spec. That would help with resolving this issue as well: https://github.com/kubermatic/kubermatic/issues/6035

Since that requires a bit more  discussion and design, converting this to an epic.

**Comment by irozzo-1A** [comment]
> Apart from splitting the default and accessible addons, it would make sense to allow specifying the manifest source per accessible addon, in the Addon Spec. That would help with resolving this issue as well: #6035

I also thought and agree with you that having the source specified should be a good improvement.

**Comment by SimonTheLeg** [comment]
The functionality described in this epic will be part of the new Applications mechanism (#7974). As a result I have moved this epic

**Comment by ahmedwaleedmalik** [comment]
All the use cases described in this Epic will be covered by the introduction of [Applications](https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/introduce-apps.md) ⚡ 

Since https://github.com/kubermatic/kubermatic/issues/7974 will take care of this. I'd propose to close this epic in favor of https://github.com/kubermatic/kubermatic/issues/7974

**Comment by ahmedwaleedmalik** [comment]
All the use cases described in this Epic will be covered by the introduction of [Applications](https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/introduce-apps.md) ⚡ 

We have already taken care of this particular scenario by allowing admins to create `ApplicationDefinitions` directly in the master cluster. Although, we are planning on enhancing the UX even further by adding support in the dashboard and probably introducing `application catalogs`. But dedicated epics and tickets will be a better place for conversations around those topics than this epic, which is not applicable anymore.

Since https://github.com/kubermatic/kubermatic/issues/7974 will take care of this. I'll close this epic in favor of https://github.com/kubermatic/kubermatic/issues/7974. 

cc @SimonTheLeg @wozniakjan @csengerszabo
