### ISSUE TITLE
Machine/NodeDeployment creation is flaky on dev

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubermatic#5502]
**What happened?**:
After creating a cluster on dev.kubermatic.io an error popped up and the `MachineDeployment` object was not created.

**What should happen?**:
The `MachineDeployment` object should be created.

**How to reproduce?**:
Seems to be flaky and only occurs sometimes.

**Environment**
- UI Version: v2.12.0+26.g8c0fe55d
- API Version:
- Domain:
  - [ ] run
  - [ ] cloud
  - [x] dev
  - [ ] locally
- Others:

**Comment by zreigz** [comment]
we have to investigate it.

**Comment by maciaszczykm** [comment]
I didn't notice it lately, @thetechnick do you still experience this issue?

**Comment by thetechnick** [comment]
I am not creating clusters often, but just today I had the same issue again.

**Comment by maciaszczykm** [comment]
Okay, so we will try to monitor that. Was this on dev.kubermatic.io? Could you check API logs next time this happens and paste them there? This is of course for all of us.

**Comment by thetechnick** [comment]
Jup, it was on dev.
I will try to get the logs, but in most cases I am not waiting for the cluster to be created - I just wonder an hour later why there are no nodes in it :)

**Comment by floreks** [comment]
mhm... the cluster gets created, but nodes are not? Seems like some internal issue, API/Controllers?

**Comment by maciaszczykm** [comment]
There is big chance that this happens because of Kubermatic restarts/updates. The current implementation is based on a retry mechanism that waits until the cluster is ready and then tries to create initial node deployments. If the retry loop will be stopped then the replicas will not be created as we do not keep the queue anywhere. If that's the problem then a solution would be to keep initial node data somewhere persisted and remove it only when the nodes are already created or the timeout has been reached.

I'll move it to the core repo as it is related mostly to the API.

cc @zreigz @lsviben

**Comment by maciaszczykm** [comment]
It should be fixed by https://github.com/kubermatic/kubermatic/pull/6064.
