### ISSUE TITLE
Remove gcr.io/google_containers from image names

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#5773]
Replace gcr.io/google_containers references with actual upstream images

xRef #5717

**Comment by xrstf** [comment]
What is left to do for this ticket?

**Comment by xmudrii** [comment]
@xrstf The `google_containers` repo is still used for some components, such as for VPA. We should make sure that we use `k8s.gcr.io` everywhere.

**Comment by xmudrii** [comment]
/remove-lifecycle stale

We still use the `google_containers` registry for VPA. I'm not really sure why's that the case, but we should look into this.

**Comment by vitality411** [comment]
Hello,
what is about calico and coredns images in customer clusters?
    Image:         docker.io/calico/cni:v3.8.0
    Image:          docker.io/calico/node:v3.8.0
    Image:         docker.io/coredns/coredns:1.3.1

KKP v2.16.8
K8s v1.20.6

**Comment by kron4eg** [comment]
Those are not related. We need to remove `gcr.io/google_containers` because upstream kubernetes have deprecated them and will stop (if not already) publishing containers in there.

**Comment by xmudrii** [comment]
What @kron4eg said is correct. Just to add on that -- the images are not published to the `gcr.io/google_containers` registry since [VDF (Vanity Domain Flip)](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/Vanity-Domain-Flip.md). The VDF happened in July 2020.

All Kubernetes images (including images for the core components and the subprojects) are published only to the `k8s.gcr.io` registry. The `k8s.gcr.io` registry was also pre-populated with the (most) images from the old registry.

Since images are not pushed to the old registry anymore, we switched to the `k8s.gcr.io` registry for all images published by the upstream Kubernetes. This is not related to other `docker.io` images and registries.

For more details on VDF and the `k8s.gcr.io` registry, you can see the document that I linked above.
