### ISSUE TITLE
Configure the networking on the User cluster VMs for the new expose strategy

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#5811]
**User Story**
The goal of this issue is to configure the networking on each worker node.

We will create a dummy interface, assign it an IP address as defined in the API Server flag `--advertise-address`. Envoy will bind to this address and listen for incoming requests.
An init container, running on the host network, will be created to handle those tasks.

**Acceptance criteria**
Dummy interface is created and assigned with the correct advertised address.

**Comment by irozzo-1A** [comment]
We finally decided not to use the dummy interface, but to bind to the existing interface in the worker. Instead of relying on `--advertise-address` in order to configure the Kubernetes service endpoints we are going to disable the KAS ep reconciliation using: https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/none.go
