### ISSUE TITLE
KubermaticConfiguration v1beta / v1

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#5971]
### User Story
This issue tracks our experiences with the v1alpha1 and the plans on improving and maturing it to v1 eventually.

### Item 1: featureGates

The current `featureGates` setup is tripping up everyone, because it's super non-obvious that it's a `map[string]struct{}` and therefore configuring means doing

```yaml
featureGates:
  featureX:
    anyNonEmpty: objectHere
```

We should probably turn this into a simple map and then perform the map->set conversion in the code at runtime, when needed.

Can we do this in-place or should we define a new `featureFlags` field and deprecate the old `featureGates`?

### Item 2: No Spec

Currently for convenience and easier migrations, we do not spec out our CRDs. This has advantages like thos mentioned, but also disadvantages regarding validation and tooling integration.

Can we spec out the CRD? Do we want to? How does this affect migrations in the future?

**Comment by erdii** [comment]
wrt to item 1: what do you think about allowing both old and new style featureGates in the same field for v1beta/v1 but log a deprecation warning if the old style was used?
The next version would then fully drop support for the old style

wrt to item 2:  :+1: speccing out the CRD would be very nice from the perspective of an administrator installing and configuring kubermatic because of all the schema validation goodness catching things like typos in field names.
