### ISSUE TITLE
API created account not visible in UI

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6247]
Problem statement:
Projects created are not visible in the UI, such projects have been created via API account.
Create an API account for the terraform provider and create only ressources - not bound to a user, therefore not visible.
API account should be traceable which should always be a user and it should be visible in the UI.

User Story:

As a user, I only want traceable accounts that can be audited so that I cannot create accounts that could pose a possible security threat.

**Comment by shaase-ctrl** [comment]
@zreigz commented:
I've checked the problem when the service account created a user cluster.
1 - service account creates a cluster for an existing project then the cluster is visible to all project members
2 - service account creates a new project and cluster in this project then SA is not set as a project owner (by design) and additionally some logged user must be added as the owner for the project. The UI doesn't handle orphaned projects. We don't support cluster creation by SA in our UI so it must be handle manually.


We will investigate how to improve this.

**Comment by zreigz** [comment]
Service accounts are considered as the project’s resources. Only the owner of the project can create a service account. 
SA shouldn't be able to create any project because it leads to the situation when we have an orphan project.
This is a bug in the API because create endpoint uses a privileged client. 
The project provider should reject calls from the SA with a forbidden error.
We should make it clear in the documentation: https://docs.kubermatic.com/kubermatic/v2.15/advanced/service_account/

**Comment by phiphi282** [comment]
Especially with the kubermatic provider for terraform it would be really nice to have some form of creating a service account that is bound to a user.
We already have customers who are using it and are creating projects with it. We are currently working around this issue by getting the token from the user out of the ui or using a project bound service account and adding users to it.

**Comment by furkhat** [comment]
The api account in editors group doesn't have access to certain resources. Not sure if it alse intended..
Having api account associated with user or just an ability to generate an access token bound to user would be nice.
