### ISSUE TITLE
KubeFlow - Istio deployment issues 

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#6260]
Investigate issues discovered by deployment of KF in KKP:

- try deploying Istio sparated from KubeFlow
- propose a startegy for Istio tweaks in KubeFlow deployment
- Istio 1.3.1+ requires k8s API server flag tweaks

(Goals: expose Istio HTTPS as a LoadBalancer service, allow to tweak Istio config for Dex)

**Comment by aborilov** [comment]
* deployed latest Istio using operator without any problem.
* commented out istio components in KubeFlow manifest and tried to deploy it, but because KubeFlow has a lot of istio configuration that's not compatible with newly deployed istio version and configuration it's not possible to do this without going through all configuration and adapting it to the deployed istio, so, we need to be very dedicated to deploying kubeflow on existing istio. Also, this will make it really hard to update to newer versions of KubeFlow.
* as for now, I propose to modify the existing Istio configuration to our needs, we already did this successfully for changing the ingress service type using overlays.
