### ISSUE TITLE
configurable image versions for user clusters

### ISSUE THREAD

**Issue by paepke** [kubermatic/kubermatic#6323]
**User Story**
Using another version of for example the machine-controller in the user cluster needs a recompilation of kubermatic as its hardcoded in https://github.com/kubermatic/kubermatic/blob/master/pkg/resources/machinecontroller/deployment.go#L56
There are possibly other parts of kubermatic and the users clusters where this could be useful.
The dashboard image version can already be set via the kubermaticconfiguration crd

The current workaround is to set a cluster into paused and edit the deployment
or using images from an own registry and retag the images there with the hardcoded tag. This has some other disadvantages and is quite dirty

**Acceptance criteria**
a specific machine-controller image can be set on runtime.
Other possible images are identified and can be set on runtime, too.

**Comment by xrstf** [comment]
>  The dashboard image version can already be set via the kubermaticconfiguration crd

What you are using is a development hack and certainly not recommended or supported for production setups, which is why we even hide it from the generated documentation: https://github.com/kubermatic/kubermatic/blob/master/pkg/crd/operator/v1alpha1/configuration.go#L106-L111

**Comment by kron4eg** [comment]
@paepke can you please explain what is the problem you are trying to fix with this move?

**Comment by paepke** [comment]
sorry for the delay - messed up my github notifications.
We had the problem that we wanted to deploy a different machine-controller version which fixed an issue. As the controller is hardcoded there was no easy to switch it to our patched version. Waiting for a new kubermatic release was not an option.
As mentioned in the original post we are aware that this was dirty and because of that we created this feature request.

**Comment by kron4eg** [comment]
It might seem like kubermatic is independent from machine-controller and that's why they are different products, but it's not really true, and they a quite tightly integrated. So we can not allow arbitrary untested-together versions of machine-controller and kubermatic.

Besides, updating machine-controller in kubermatic is really easy. It's simple bump up the version in Go source https://github.com/kubermatic/kubermatic/blob/05c514278b33bbd6cf7d65b70d32ef0c56eb9cc5/pkg/resources/machinecontroller/deployment.go#L55 and updating fixtures with `go test ./pkg/resources/... -update` (+ PR of course).

Hope that explains good enough why this issue is getting closed.
