### ISSUE TITLE
Cluster creation deadlock on openstack v2.15.3

### ISSUE THREAD

**Issue by furkhat** [kubermatic/kubermatic#6341]
There is a deadlock in cluster creation on Openstack.

1. Machine controller can't create machine because there is no crd's.
2. Metrics-server can't start because it lacks permissions
3. API server fails because it tries to connect to metrics server which is failing (2)
4. User cluster controller manager fails because it can't access coredns deployment that is not created because there are no machines (1)

I will send a pull request with a possible solution shortly.

**Comment by irozzo-1A** [comment]
Hi @furkhat,
Is this issue impacting v2.15.3 in particular? did you try newer or previous patch versions?

> 4. User cluster controller manager fails because it can't access coredns deployment that is not created because there are no machines (1)

The user cluster controller should be able to run even without machines being present, the only requirement is KAS to be available, otherwise, we could definitely end-up in a chicken-egg problem.

**Comment by furkhat** [comment]
Now when I think of it, it shouldn't have mattered if machines are present or not, and deployment should have been created anyway.. I don't know why, but the controller was failing to ensure deployments..

This is what I saw when I tested on v2.15.3:
1. User cluster controller reconciliation was failing to ensure deployments
2. Machine controller was failing because crd's were not created by user cluster controller (they are created later after deployments)
3. metrics-server was failing because it didn't have permissions to read configmaps (controller adds permission after ensuring deployments)
4. api server fails because metrics server is down

I will test again and try to understand what was the real cause of controller failing creating deployments.

Regardless of it, I think we could eliminate undesired cause and effect here. The cause being deployments creation failure and effect being block of others components dependencies. This is what I tried in #6342

**Comment by irozzo-1A** [comment]
I see, but I think that we should first identify the root cause of your issue and only after thinking about a solution. I did not manage to reproduce in our dev environment with a later version of KKP. Could you please share any relevant logs (e.g. apiserver, metrics-server, user-cluster-controller)?

**Comment by furkhat** [comment]
I couldn't reproduce the issue and I don't know why, but even with the same version of KKP I can't reproduce it. (Though at the time it was occurring very consistently). I guess it is due to certain order of events I am not replaying or completely something else that I cannot see at the moment.

We will keep the changes from #6342 in our fork just to be sure we are protected from possibility of the same problem occurring. It will be understandable if you decide to reject and close the #6342.
