### ISSUE TITLE
Cluster stuck in deletion Openstack when there are PersistentVolumes and no worker nodes

### ISSUE THREAD

**Issue by furkhat** [kubermatic/kubermatic#6406]
Steps to reproduce:
  1. Create Openstack cluster with worker nodes, wait for cluster to get healthy
  2. Then deploy some applications which would claim persistent storage, wait for them to be ready
  3. Then delete all worker nodes by deleting all node deployments, wait for it to finish
  4. Then delete the cluster.
  5. The cluster should be stuck in deletion.

Kubermatic deploys [csi addon](https://github.com/kubermatic/kubermatic/blob/master/addons/csi/controllerplugin.yaml#L44) on worker nodes, `csi-cinder-controllerplugin` is responsible for adding and deleting `external-attacher/cinder-csi-openstack-org` finalizer from PersistentVolumes and VolumeAttachments. When we delete all nodedeployments `csi-cinder-controllerplugin` will be down and won't be able to schedule because it needs worker nodes to run on.
When cluster is being deleted and cleaning up procedure issues deletion of in-cluster PersistentVolumes thay won't be deleted because they will have `external-attacher/cinder-csi-openstack-org` on them.

**Comment by wozniakjan** [comment]
I suppose we would like to have a little more elaborate cleanup logic. I think we don't want to delete a node that is running a `csi-cinder-controllerplugin` unless all `PVs` belonging to this CSI plugin are correctly deleted, is that correct?

I can imagine two different ways to address it:

1. set up some sort of cascade garbage collection using finalizers on OpenStack `Nodes` and `MachineDeployments`. Perhaps a finalizer on `MachineDeployment`, when it is being deleted, we know those `PVs` should get deleted but we need to prevent `csi-cinder-controllerplugin` from getting removed first. The controller for `MachineDeployments` can invoke cleanup logic on delete (deleting `PVCs` and `PVs` belonging to  `csi-cinder-controllerplugin`) and remove its finalizer only when it's done (the `PVCs` and `PVs` no longer have `external-attacher/cinder-csi-openstack-org` finalizer). After that we trigger deletion of `Nodes` and `Pods`, but because `csi-cinder-controllerplugin` has done its clean up job, we should be in better shape. I think we also need to ensure that when `MachineDeployments` is being deleted, we reject cinder `PVs` and `PVCs`.
2. dynamic admission control webhook on `DELETE` for `Nodes` requiring at least one node to be present if there are any `PVs` or `PVCs` with `external-attacher/cinder-csi-openstack-org` finalizer.

I will play around with the problem a little bit more and see if I get any better ideas. So far not terribly excited about either of my proposals.

**Comment by wozniakjan** [comment]
@irozzo-1A proposed likely superior solution, moving `csi-cinder-controllerplugin` to the seed cluster.

UPDATE: at standup, it was mentioned that CSI cinder plugin is deployed using addons in seed-controller-manager. The plugin consists of two parts:
* `csi-cinder-nodeplugin` - attach/detach `DaemonSet`, this and all related manifests need to be deployed in the user cluster
* `csi-cinder-controllerplugin` - PV provisioner `StatefulSet`, this is what we would potentially move to the seed cluster and point it to watch user cluster API.

In conjunction with https://github.com/kubermatic/kubermatic/issues/6759, this should help with successful cluster deletion and no dangling volumes left in OpenStack

**Comment by wozniakjan** [comment]
https://github.com/kubermatic/kubermatic/pull/7037 proposes to allow addon to be installed partially in user cluster and partially in seed cluster to appropriate namespace.

**Comment by wozniakjan** [comment]
I had a little bit of time today to test the problem more thoroughly. It looks like when I create a `PVC`, let it bind to a `PV`, then just delete the `PVC`, cinder plugin cleans up the `PV` as well as the volume on OpenStack. But deleting the `PV` manually along with deleting the `PVC` to mimic the cluster deletion code results in successful deletion of kubernetes resources but leaves the OpenStack volume still present.

https://github.com/kubermatic/kubermatic/blob/0eef31d0eca5bfa4e693aeee7677a080f81e119d/pkg/clusterdeletion/volumes.go#L76-L81

I will see if this is something we can adjust easily in the `clusterdeletion` package or if this should be fixed as a patch to the cinder plugin.

**Comment by wozniakjan** [comment]
/remove-lifecycle stale
just slow due to time allocation and prioritization of other tasks :)

**Comment by furkhat** [comment]
/remove-lifecycle stale
Feel free to close this if it fixed

**Comment by wozniakjan** [comment]
> Feel free to close this if it fixed

I believe this has been fixed by two PRs https://github.com/kubermatic/kubermatic/pull/7189 and https://github.com/kubermatic/kubermatic/pull/6990. For additional resiliency, we thought it would be nice to split the addon between seed and user cluster as documented in https://github.com/kubermatic/kubermatic/pull/7413, but I have been swarmed by other high priority tasks so didn't get that across the finish line.

I will keep this open as a reminder about https://github.com/kubermatic/kubermatic/pull/7413 for now.

**Comment by shaase-ctrl** [comment]
@wozniakjan Do we work on this in the future?

**Comment by wozniakjan** [comment]
@shaase-ctrl given no one complained after the low hanging fruit got fixed in https://github.com/kubermatic/kubermatic/pull/6990 and https://github.com/kubermatic/kubermatic/pull/7189, let's close https://github.com/kubermatic/kubermatic/pull/7413 without merge and this ticket too. If problems reappear, we at least know how to move forward with https://github.com/kubermatic/kubermatic/pull/7413 and can attempt to finish it.
