### ISSUE TITLE
Vendoring: migrate to Glide

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#66]
I want to discuss here the pros and cons to migrate from godep to [Glide](https://github.com/Masterminds/glide)

In general the update process with godep and k8s is quite tricky and the problem we had with `log_dir` #63 was due to the fact that the dependencies was not correctly resolved.

Also as we got this fixed, new things comes up e.g `install.go` was missing.
You can compare our repo
https://github.com/kubermatic/api/tree/sch-upgrade-godeps/vendor/k8s.io/kubernetes/pkg/apis/authentication.k8s.io
with the k8s repo
https://github.com/kubernetes/kubernetes/tree/v1.3.5/pkg/apis/authentication.k8s.io

I migrate to Glide and the dependencies issues where resolved
https://github.com/kubermatic/api/pull/65/commits/141414246c5d0ba9631dac7c41a372ab729caf1e 

Pros:
- easier dependencies updates
- direct download of dependencies in vendor folder (no bloating of src)
- vendor folder could be removed from git 

Cons:
- currently Glide download more files then godep (when we change to k8s client lib, this will reduce the files size dramatically )

Let me know, what you think or if you see another alternative.

**Comment by sttts** [comment]
Everything is better than godeps.

**Comment by s-urbaniak** [comment]
I do recommend moving to glide, sooner than later. There are a few gotchas though:
1. By default your vendor directory will be huge. You have to strip the vendor directory using https://github.com/sgotti/glide-vc.
2. There is no `godep restore`, but that actually is not necessary, since Go now supports `vendor` first-class.

For inspiration, you can see how I did in rkt: https://github.com/coreos/rkt/pull/2735#issue-157927065
