### ISSUE TITLE
Failing deployments with insufficient CPU capacity for controller manager

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6609]
**User Story**

As a user, I want to be able to successfully deploy even larger sets so that I am not limited by the component restrictions.

Problem description by customer (translated):

We had the problem in some deployments that the controller manager was not schedulable due to insufficient CPU capacity (2 CPU).
We would like to solve this by giving the pods a priorityClassName and thus making room for the pods in such a case.
This is not possible to configure at the moment (at least for the Helm chart).
Has anything changed in the operator in this regard? If not, we would like to request this as a feature. I think this is interesting for all users of Kubermatic.

**Acceptance criteria**
- Evaluate if the component should be configurable or scalable
- Evaluate if the  priorityClassName would solve these issues without creating new ones
- Create a proposal

**Comment by squ94wk** [comment]
**Scenario:**
The scenario arises, when there's any Kubermatic component that has high resource requests.
The Kubermatic controller manager is such a component.

**Example:**
I install KKP on a cluster with nodes with 8 CPU each.
Workloads are evenly distributed on these nodes and request 6.01 CPUs on each node (~75% utilization).
A new pod (for example during a rollout) requests 2 CPU.
The Pods will not be schedulable, since there's no node with enough resource capacity.
I will have to manually delete pods to make room. Otherwise the pod will get stuck in *Pending*.

This is the worst case scenario, but very realistic.
To guarantee that the Pod can be scheduled I consistently keep the number of nodes high enough to stay below 75% utilization. If using autoscaling, this is not feasible.

**Possible Workarounds:**
One could use taints to dedicate special nodes to Kubermatic components. This makes capacity planning, scheduling and autoscaling more complicated.

One could use bigger nodes, but this might be less flexible and may cause longer drains.

> Evaluate if the component should be configurable or scalable

While the component can be scaled, I believe this is only for HA purposes and a leader is elected that runs the main loop.
This would not remediate any issues with scheduling and capacity.
I think rewriting the controller to support horizontal scaling is not feasible or not sensible.

> Evaluate if the priorityClassName would solve these issues without creating new ones

For Pods without `priorityClassName` set, Kubernetes either assumes a default Priority Class, or uses priority value `0`, so nothing changes for those.
Giving a component a higher priority, may lead to preemption of other pods with lower priority to make room on a node.
Other workloads on K8s should already be designed to tolerate this behavior.
The concept of priority is designed to be orthogonal to other scheduling features, such as taints or affinity.

**Proposal:**
I propose to add parameters to the KKP installation for each component's configuration that allow to pass a `priorityClassName` to individual Kubermatic components. The default should remain the empty value, so no priority class.
The value is used when templating the manifest for each component.
The installer should assume that the `PriorityClass` already exist.

This solves the issue described above, since the Pod, having a higher priority, will always be schedulable, as long as my cluster has enough resources (or other pods with become stuck in *Pending*). My utilization is no longer bound by single large workloads and can theoretically approach 100%.

**Comment by irozzo-1A** [comment]
Hi @squ94wk,

Thx for creating this issue.

I agree that having a workload with large requests compared to the size of the nodes could end up in fragmentation and low total_request/total_available_resource ratio (probably actual resource utilization is more interesting though :-)).

If I'm not mistaken you are referring to a seed cluster and in particular to `seed-controller-manager`, the default in k8c 2.15 is to have 1 replica with a CPU request of `512Mi`:

https://github.com/kubermatic/kubermatic/blob/227cecc73579a60c1f43f0cc436fe0bdbd213b7d/charts/kubermatic/values.yaml#L130-L136

https://github.com/kubermatic/kubermatic/blob/227cecc73579a60c1f43f0cc436fe0bdbd213b7d/pkg/controller/operator/common/defaults.go#L105-L108

Did you change the default to 2 CPUs? In such case could you please provide some more details about the reason (maybe some figures)?

> To guarantee that the Pod can be scheduled I consistently keep the number of nodes high enough to stay below 75% utilization. If using autoscaling, this is not feasible.

I'm not sure of getting your point here. I think you are referring to [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#when-does-cluster-autoscaler-change-the-size-of-a-cluster), could you please clarify why it's not fitting your needs? 

In addition, I have two general comments:
* Priority should be used to define the importance of a pod, e.g. dns or cni pods are critical for the cluster to work properly, so it's fair that it has higher priority with respect to other infrastructure pods. Using priority in this context seems a slight abuse to me :-).
* Having a CPU request that is lower than the limit is probably acceptable for the seed-controller-manager, considering that it has very likely a bursty behavior.

**Comment by squ94wk** [comment]
Hi @irozzo-1A,

thanks for the reply.

In our KKP installation we run enough clusters that the seed-controller-manager usually uses 2-3 vcpu constantly with peaks here and there of up to 4, so we request 2 CPU and have limits of 6.

> I think you are referring to cluster-autoscaler, could you please clarify why it's not fitting your needs?

I guess with the autoscaler I was wrong.

> Using priority in this context seems a slight abuse to me

I agree that CNI, CSI, DNS etc Pods should have the highest priority.
However, while they're critical for a node, I would consider the seed-controller-manager critical for Kubermatic, more important than the user cluster components for example. I'd like Kubernetes to preempt pods from a user cluster namespace in favor of scheduling the seed-controller-manager.
That's why I think applying priority to KKP pods would the appropriate tool here.

> Having a CPU request that is lower than the limit is probably acceptable for the seed-controller-manager, considering that it has very likely a bursty behavior.

We could user lower requests, but the pod hardly ever uses less than 2 cores.
