### ISSUE TITLE
Orphaned resources

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#6624]
**User Story**
The kubermatic-master-ctrlmgr is logging lots and lots of these errors:

> {"level":"error","ts":1614771655.9472706,"logger":"controller-runtime.manager.controller.rbac_generator_resources","msg":"Reconciler error","name":"kubeconfig-external-cluster-fxfq4zhrb8","namespace":"kubermatic","error":"unable to find owning project for the object name = kubeconfig-external-cluster-fxfq4zhrb8, gvr = &{/v1, Resource=secrets /v1, Kind=Secret %!s(*meta.restScope=&{namespace})}","stacktrace":"(...snip...)"}

and 

> {"level":"error","ts":1614771865.1469944,"logger":"controller-runtime.manager.controller.rbac_generator_resources","msg":"Reconciler error","name":"credential-digitalocean-hp7s2brln7","namespace":"kubermatic","error":"unable to find owning project for the object name = credential-digitalocean-hp7s2brln7, gvr = &{/v1, Resource=secrets /v1, Kind=Secret %!s(*meta.restScope=&{namespace})}","stacktrace":"(...snip...)"}

This is happening with the current master branch, but probably also affects 2.16.x.

**Acceptance criteria**
- [ ] These errors do not happen anymore.
- [ ] If 2.16 is affected, a bugfix is backported and a fixed release is produced.

**Comment by zreigz** [comment]
This problem was fixed some time ago: https://github.com/kubermatic/kubermatic/blob/master/pkg/provider/kubernetes/credentials.go#L95

The errors come from some orphaned secrets for user cluster credentials. I removed them because they were missing the `projectID` label and parent clusters were deleted a long time ago. Now should be fine.  

Please reopen when the problem still exists.
