### ISSUE TITLE
Missing cluster finilazers due to possible data race

### ISSUE THREAD

**Issue by furkhat** [kubermatic/kubermatic#6759]
**Steps to reproduce:**
 * I create openstack cluster
 * I see cloud [openstack InitializeCloudProvider function](https://github.com/kubermatic/kubermatic/blob/master/pkg/provider/cloud/openstack/provider.go#L158) created resources in openstack
 * When later I check cluster finalizers by running kubectl describe
 * I see [the finalizers](https://github.com/kubermatic/kubermatic/blob/master/pkg/provider/cloud/openstack/provider.go#{L45:L58}) are missing
 
I debugged and found that finalizers were added and deleted shortly after. I found that finalizers added by [openstack InitializeCloudProvider function](https://github.com/kubermatic/kubermatic/blob/master/pkg/provider/cloud/openstack/provider.go#L158) were deleted by following update here https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/seed-controller-manager/kubernetes/pending.go#L90

I was able to fix the bug by reverting reverting changes introduced #4578

**Kubermatic version:** `v2.16.5`

**Comment by zreigz** [comment]
cc @moadqassem @xrstf

**Comment by furkhat** [comment]
Ultimately the problem is that if I send merge patch request to update `finalizers` field it will just replace the array. I can verify that by running `kubectl patch cluster CLUSTER_HERE -p '{"metadata":{"finalizers":["foo"]}}' --type merge`, after this command old items are gone

**Comment by furkhat** [comment]
[MergeFrom](https://github.com/kubernetes-sigs/controller-runtime/blob/e10bf72058d349e9c5cdd177593c32c650065458/pkg/client/patch.go#L151) uses `--type merge` like with kubectl. Which is ok when we delete finalizers, but not ok when we add (**Edit:** actually even with delete it isn't ok, because we might loose finalizers and have resources that block cluster deletion #6934 ).

**Comment by furkhat** [comment]
It seems like it was added to recent release of controller-runtime https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.8.3

**Comment by furkhat** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md

**Comment by furkhat** [comment]
> What we need is strategic merge (kubernetes strategic merge docs)

Unfortunately I was wrong because it seems that strategic merge patches are not supported for custom resource definitions. That's what [the doc](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#summary) says at the very end and that's what error says when I try to do it on cluster.

**Comment by furkhat** [comment]
I am looking now at server side apply https://kubernetes.io/docs/reference/using-api/server-side-apply (basically each controller can create a lock on specific fields. All active locks are listed in `metadata.managedFields`).

**Comment by furkhat** [comment]
I wrote a program to reproduce data loss. It performs two patches to add finalizers `foo` and `bar`. If you execute it the final result contains `bar` finalizer from last patch, but doesn't contain finalizer `foo`.
```go
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/pkg/errors"
	kubermaticv1 "k8c.io/kubermatic/v2/pkg/crd/kubermatic/v1"
	kuberneteshelper "k8c.io/kubermatic/v2/pkg/kubernetes"
	ctrlruntime "sigs.k8s.io/controller-runtime"
	ctrlruntimeclient "sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

func main() {
	clusterName := flag.String("cluster", "", "cluster name")
	flag.Parse()
	if *clusterName == "" {
		flag.Usage()
		os.Exit(1)
	}

	cfg := ctrlruntime.GetConfigOrDie()
	mgr, err := manager.New(cfg, manager.Options{})
	if err != nil {
		panic(err)
	}
	go func() {
		if err := mgr.GetCache().Start(context.Background()); err != nil {
			panic(err)
		}
	}()

	client := mgr.GetClient()

	if ok := mgr.GetCache().WaitForCacheSync(ctrlruntime.SetupSignalHandler()); !ok {
		panic("cache is not ready")
	}

	var cluster kubermaticv1.Cluster
	if err := client.Get(context.Background(), ctrlruntimeclient.ObjectKey{"kubermatic", *clusterName}, &cluster); err != nil {
		panic(err)
	}
	cluster.SetManagedFields(nil)

	var clusterCopy kubermaticv1.Cluster
	if err := client.Get(context.Background(), ctrlruntimeclient.ObjectKey{"kubermatic", *clusterName}, &clusterCopy); err != nil {
		panic(err)
	}
	clusterCopy.SetManagedFields(nil)

	if err := patch(client, &cluster, "foo"); err != nil {
		log.Panicf("foo: %v", err)
	}
	if err := patch(client, &clusterCopy, "bar"); err != nil {
		log.Panicf("bar: %v", err)
	}
	fmt.Println("done")
}

func patch(client ctrlruntimeclient.Client, cluster *kubermaticv1.Cluster, finalizers ...string) error {
	oldCluster := cluster.DeepCopy()
	kuberneteshelper.AddFinalizer(cluster, finalizers...)
	if err := client.Patch(context.Background(), cluster, ctrlruntimeclient.MergeFrom(oldCluster)); err != nil {
		return errors.Wrap(err, "patch cluster")
	}
	return nil
}
```

---

Here is how server-side apply would look. Here I patch finalizers by using `PartialObjectMetadata` because if I use `kubermaticv1.Cluster` I locks for more fields than I need.
```go
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/pkg/errors"
	kubermaticv1 "k8c.io/kubermatic/v2/pkg/crd/kubermatic/v1"
	kuberneteshelper "k8c.io/kubermatic/v2/pkg/kubernetes"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrlruntime "sigs.k8s.io/controller-runtime"
	ctrlruntimeclient "sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

func main() {
	clusterName := flag.String("cluster", "", "cluster name")
	flag.Parse()
	if *clusterName == "" {
		flag.Usage()
		os.Exit(1)
	}

	cfg := ctrlruntime.GetConfigOrDie()
	mgr, err := manager.New(cfg, manager.Options{})
	if err != nil {
		panic(err)
	}
	go func() {
		if err := mgr.GetCache().Start(context.Background()); err != nil {
			panic(err)
		}
	}()

	client := mgr.GetClient()

	if ok := mgr.GetCache().WaitForCacheSync(ctrlruntime.SetupSignalHandler()); !ok {
		panic("cache is not ready")
	}

	var cluster kubermaticv1.Cluster
	if err := client.Get(context.Background(), ctrlruntimeclient.ObjectKey{"kubermatic", *clusterName}, &cluster); err != nil {
		panic(err)
	}
	cluster.SetManagedFields(nil)

	var clusterCopy kubermaticv1.Cluster
	if err := client.Get(context.Background(), ctrlruntimeclient.ObjectKey{"kubermatic", *clusterName}, &clusterCopy); err != nil {
		panic(err)
	}
	clusterCopy.SetManagedFields(nil)

	if err := patch(client, &cluster, "foo-controller", "foo"); err != nil {
		log.Panicf("foo: %v", err)
	}
	if err := patch(client, &clusterCopy, "bar-controller", "bar"); err != nil {
		log.Panicf("bar: %v", err)
	}
	fmt.Println("done")
}

func patch(client ctrlruntimeclient.Client, cluster *kubermaticv1.Cluster, controller string, finalizers ...string) error {
	patch := &metav1.PartialObjectMetadata{
		TypeMeta: cluster.TypeMeta,
		ObjectMeta: metav1.ObjectMeta{
			Name:       cluster.Name,
			Namespace:  cluster.Namespace,
			Finalizers: cluster.Finalizers,
		},
	}
	owner := ctrlruntimeclient.FieldOwner(controller)
	patch.SetManagedFields(nil)
	// Claim shared ownership
	if err := client.Patch(context.Background(), patch, ctrlruntimeclient.Apply, owner); err != nil {
		return errors.Wrap(err, "claim shared ownership")
	}
	// Patch finalizers
	kuberneteshelper.AddFinalizer(patch, finalizers...)
	patch.SetManagedFields(nil)
	if err := client.Patch(context.Background(), patch, ctrlruntimeclient.Apply, owner, ctrlruntimeclient.ForceOwnership); err != nil {
		return errors.Wrap(err, "add finalizers")
	}
	return nil
}
```

This results with following error, which I think is what we need.
```
panic: bar: claim shared ownership: Apply failed with 1 conflict: conflict with "foo-controller": .metadata.finalizers
```

WDYT @irozzo-1A ?

**Comment by irozzo-1A** [comment]
Hi @furkhat, first of all, thx for your analysis. I think you are quite right about the race condition.
We have several controllers adding finalizers to the cluster object, and the following scenario is probably happening:

1. Controller `A` gets Cluster `foo`
1. Controller `B` gets Cluster `foo`
1. Controller `A` updates cluster `foo` adding finalizer `kubermatic.io/finalizer-1` (does not matter how)
1. Controller `B` adds finalizer `kubermatic.io/finalizer-2` to its local version of `foo` not containing the finalizer `kubermatic.io/finalizer-2` 
1. Controller `B` generates the following patch of type `application/merge-patch+json` from its local version of cluster `foo` using [MergeFrom](https://github.com/kubernetes-sigs/controller-runtime/blob/a8c19c49e49cfba2aa486ff322cbe5222d6da533/pkg/client/patch.go#L140-L143) resulting in:
```{"metadata":{"finalizers":["kubermatic.io/finalizer-2"]}}```
instead of:
```{"metadata":{"finalizers":["kubermatic.io/finalizer-1", "kubermatic.io/finalizer-2"]}}```
1. Controller `B` applies the patch overriding `kubermatic.io/finalizer-2`

As you pointed out when we were using `Update` instead of `Patch`, we were not vulnerable to this race due to the optimistic locking. The easiest thing I can think of is to use [MergeFromWithOptions](https://github.com/kubernetes-sigs/controller-runtime/blob/a8c19c49e49cfba2aa486ff322cbe5222d6da533/pkg/client/patch.go#L145-L152) in conjunction with [MergeFromWithOptions](https://github.com/kubernetes-sigs/controller-runtime/blob/a8c19c49e49cfba2aa486ff322cbe5222d6da533/pkg/client/patch.go#L59-L68):

```
ctrlruntimeclient.MergeFromWithOptions(oldCluster, ctrlruntimeclient.MergeFromWithOptimisticLock{})
```

This should make it IMO. Do you want to try it?

**Comment by irozzo-1A** [comment]
I was taking a look at https://github.com/kubermatic/kubermatic/pull/4578, the fix I proposed of course would probably require having the retry logic back and make the usage of Patch less effective, I'll check if we have a better alternative.

**Comment by furkhat** [comment]
> The easiest thing I can think of is to use MergeFromWithOptions in conjunction with MergeFromWithOptions:
> ctrlruntimeclient.MergeFromWithOptions(oldCluster, ctrlruntimeclient.MergeFromWithOptimisticLock{})
> This should make it IMO. Do you want to try it?

I considered it and it does not look good. It fails every time resourceVersion is changed, and it seems resourceVersion changes all the time, even if cluster.spec and cluster.metadata have not changed. Also I don't like that it is logic on client side - it depends on client side cache which can be unsync with actual state.

So far the best approach I found is to use patch with server-side apply. Pros of this approach is: 1) allows to claim ownership on specific fields in the resource 2) ownership can be shared between several controllers if their state of the fields are in sync 3) everything happens on server side.

**Comment by irozzo-1A** [comment]
@furkhat Definitely the SSA is something we want to experiment with, but after discussing with @mfranczy we consider this option not optimal for a quick fix, as it requires to be carefully studied, and prepared (e.g. identifying the ownership of each field in `Cluster` resource, defining the appropriate merge strategy).

> I considered it and it does not look good. It fails every time resourceVersion is changed, and it seems resourceVersion changes all the time, even if cluster.spec and cluster.metadata have not changed. Also I don't like that it is logic on client side - it depends on client side cache which can be unsync with actual state.

`resourceVersion` changes every time the resource is written, you're right on this. On the other hand, we should adopt optimistic locking only where it is actually needed, that is when we have a field that is managed by multiple controllers (e.g. finalizers). So we can target only the "problematic" updates and try to group them as much as we can to reduce the contention points.

When we encounter a conflict, we should not try to repeat the same reconcile iteration (as it was before #4578), because as you pointed out we rely on a "cached" client. We have two options:
1. We use a direct client on retry
2. We just return an error and we retry on the next reconcile iteration

The second approach is preferable, as it is more respectful of controller semantics.

I started applying this concept, in the draft PR I opened (#6990), and those are the key aspects:

1. We add all the finalizers that are required before starting provisioning the cloud resources with optimistic locking activated, this is safe as far as the clean-up procedure is idempotent. We return immediately on conflict.
https://github.com/kubermatic/kubermatic/blob/4706b1a947453acf4506bbe92cc80b477889d178/pkg/provider/cloud/openstack/provider.go#L175-L198
2. Similarly we remove all finalizers in one shot with optimistic locking after all resources have been cleaned up:
https://github.com/kubermatic/kubermatic/blob/4706b1a947453acf4506bbe92cc80b477889d178/pkg/provider/cloud/openstack/provider.go#L359-L371

If we generalize this approach for all providers we should avoid the race.
WDYT @mfranczy ?

**Comment by mfranczy** [comment]
I agree with @irozzo-1A, SSA needs to be implemented carefully and each field should have a clear ownership, currently finalizers field is being modified by multiple controllers, IMO we should refactor this.

Additionaly for SSA it's recommended for controllers to [force conflicts](https://kubernetes.io/docs/reference/using-api/server-side-apply/#using-server-side-apply-in-a-controller), the finalizers field should not cause them but in other cases the problem might appear (more complex structures).

I am willing to work on SSA implementation but this cannot be applied as a hot fix, the optimistic lock proposed by @irozzo-1A is good enough for now.


> We just return an error and we retry on the next reconcile iteration
The second approach is preferable, as it is more respectful of controller semantics.

I vote for the second approach instead of using direct client.

**Comment by furkhat** [comment]
Sounds good! When #6990 is ready I will test it out on our environment.

**Comment by irozzo-1A** [comment]
> Sounds good! When #6990 is ready I will test it out on our environment.

@furkhat It's merged, you can test it if you wish ;-)

**Comment by furkhat** [comment]
@irozzo-1A I think few more places need optimistic lock to ensure finalizers are not overwritten.

In seed controller for backup_controller [here](https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/seed-controller-manager/backup/backup_controller.go#L291).

And in master controller for usersshkeysynchroniser controller [here](https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/master-controller-manager/usersshkeyssynchronizer/controller.go#L210) (the likelihood of race occurring here might be higher because master controller and seed controllers are different processes and they have different instances of go-client cache).

**Comment by irozzo-1A** [comment]
Thx @furkhat, those are definitely good points. I'll take a quick look to see if there are other places we may have overlooked. BTW the second you pointed out is a funny one because we use a patch for adding finalizer and update to remove.
