### ISSUE TITLE
Constraints getting stuck in deletion

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#6934]
Sometimes after OPA-enabled cluster deletion, with active constraints, the constraints dont get deleted properly, meaning they are left with finalizers and thus cause the user cluster namespaces on the seed cluster to be stuck as well. 

Investigate and fix the reason for this.

```
$ k get ns
NAME                                 STATUS        AGE
namespace/cert-manager               Active        517d
namespace/cluster-4wzv54h8xr         Terminating   6d1h
namespace/cluster-52rlpk7cvm         Active        38m
namespace/cluster-9mz4mwvdt8         Active        3h51m
namespace/cluster-fpcm4m7x8b         Active        9d
namespace/cluster-gngb9dbgpz         Active        85m
namespace/cluster-gpv45s4qdx         Active        38m
namespace/cluster-lbpdsvnfgn         Terminating   6d3h
namespace/cluster-ldkqklqlmc         Active        7d3h
namespace/cluster-lv7smcfnp4         Active        3h50m
namespace/cluster-snipoc             Active        320d
namespace/cluster-vbw2sgswnl         Active        3h51m
namespace/default                    Active        3y185d
namespace/envoy                      Active        331d
...
$ k -n cluster-4wzv54h8xr get constraints.kubermatic.k8s.io
NAME   AGE
test   6d
$ k -n cluster-lbpdsvnfgn get constraints
NAME   AGE
test   6d1h
```

**Comment by furkhat** [comment]
This could be related to #6759

**Comment by lsviben** [comment]
> This could be related to #6759

Thanks for the heads-up, yes it could be related. Ill consider it during investigation

**Comment by jiachengxu** [comment]
If we check the status of the user-cluster namespace which is in `Terminating` status, we can see that this is a finalizer on the `Constraint` objects which will block the deletion of `Constraint`:
```yaml
- lastTransitionTime: "2021-05-31T02:21:21Z"
   message: 'Some content in the namespace has finalizers remaining: kubermatic.io/cleanup-gatekeeper-constraints
     in 1 resource instances'
     reason: SomeFinalizersRemain
     status: "True"
     type: NamespaceFinalizersRemaining
```
and this finalizer `kubermatic.io/cleanup-gatekeeper-constraints` is managed by [user-cluster-controller-manager/constraints-syncer](https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go#L126-L138).
When a user cluster is being deleted, there is a race condition between:
1. User cluster controller manager deployment(pod) is deleted.
2. User cluster controller manager removes the finalizer `kubermatic.io/cleanup-gatekeeper-constraints`

If 1 happens before 2, then the user cluster controller manager will not be able to remove finalizers on `Constraint` objects, and which will block deletion of the user cluster namespace.

## Proposed Solutions
- Solution 1: Move the constraint syncer a level above - seed controller manager. In that case, the seed controller manager can remove the finalizer from the Constraint when the cluster is being deleted. The limitation of this approach is scalability because the seed controller manager will need to sync all user constraints to all user clusters, that may cause some scalability issues in some large-scale setup which contains many user clusters.
- Solution 2: Add logic just to remove the finalizer on the seed controller manager.  In this case, when the user cluster is being deleted, the seed controller manager will remove the finalizer on the `Constraint` in the user-cluster namespace in the Seed cluster, so that `Contraint` can be removed successfully. Note that we can tolerate that there may be some `Constraints` resources left in the user cluster because the whole cluster will be removed anyway.

After discussing with @lsviben and @imharshita, we would implement solution 2 since that doesn't increase much work on seed controller manager and can be scaled well.
