### ISSUE TITLE
2.16 Documentation states tool that got removed

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubermatic#6946]
The 2.16 docs tell me to use `docker run --rm quay.io/kubermatic/api:KUBERMATIC_VERSION kubermatic-operator-util defaults`
here https://docs.kubermatic.com/kubermatic/v2.16/advanced/versions_updates/ .

But the command is missing or better was removed (https://github.com/kubermatic/kubermatic/pull/6420)?

How do i know get the default?

**Comment by dermorz** [comment]
`kubermatic-operator-util` is still being mentioned in these places:

```
content/kubermatic/v2.16/advanced/versions_updates/_index.en.md
content/kubermatic/v2.16/advanced/addons/_index.en.md
content/kubermatic/v2.17/guides/addons/_index.en.md
content/kubermatic/master/guides/addons/_index.en.md
```

Since it was removed in 2.16, these pages should be updated. They already refer to the documented example configuration (https://docs.kubermatic.com/kubermatic/v2.17/tutorials_howtos/kkp_configuration/), so the paragraph mentioning `kubermatic-operator-util` to obtain the default configuration can be omitted.

**Comment by dermorz** [comment]
From `v2.18.0` on the `kubermatic-installer` can print the default configuration:
```bash
$ docker run --rm quay.io/kubermatic/api:v2.18.0 kubermatic-installer print 2>&1 | head
apiVersion: operator.kubermatic.io/v1alpha1
kind: KubermaticConfiguration
metadata:
  name: <<mykubermatic>>
  namespace: kubermatic
spec:
  # API configures the frontend REST API used by the dashboard.
  api:
    # AccessibleAddons is a list of addons that should be enabled in the API.
    accessibleAddons:
...
```

But for Versions `>=v2.16<v2.18` it's not possible to get the default configuration printed out in the shell.

@shaase-ctrl Is that okay or do we need a backport of `kubermatic-installer print`? If not, this issue here can be closed and we should open another issue in the https://github.com/kubermatic/docs to remove references of the removed command.

**Comment by shaase-ctrl** [comment]
I do not think we need to backport this. Add a line to the documentation that is works with 2.18.

**Comment by dermorz** [comment]
This issue was addressed by https://github.com/kubermatic/docs/pull/843

/close
