### ISSUE TITLE
Creating rhel machine deployment fails on GCP

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#6949]
KKP dashboard proposes redhat as an option for workers os, but when selecting it the md deployment fails with the following error:

`failed  to create initial MachineDeployment: admission webhook  "machine-controller.kubermatic.io-machinedeployments" denied the  request: validation failed: An error of type = InvalidConfiguration,  with message = Invalid or not supported operating system specified  "rhel": os not supported occurred`

![rhel-err](https://user-images.githubusercontent.com/78943096/116236942-44aef780-a77d-11eb-8da8-35eef2f0826b.png)

**Comment by kron4eg** [comment]
The exact same reason (and mitigation) as in #6932

**Comment by zreigz** [comment]
new issue for the UI: https://github.com/kubermatic/dashboard/issues/3323

**Comment by moadqassem** [comment]
@harshita-sharma012 Actually RHEL is supported in GCE, Please take a look at the documentation page in the machine controller. Your deployment was failing because you need to specify a custom image for it, because at the time this was added, there was no GA images for RHEL 8 in GCP. Please take a look at the link below: 
https://github.com/kubermatic/machine-controller/blob/master/docs/rhel-custom-image.md

**Comment by moadqassem** [comment]
@imharshita  Actually RHEL is supported in GCE, Please take a look at the documentation page in the machine controller. Your deployment was failing because you need to specify a custom image for it, because at the time this was added, there was no GA images for RHEL 8 in GCP. Please take a look at the link below: 
https://github.com/kubermatic/machine-controller/blob/master/docs/rhel-custom-image.md
