### ISSUE TITLE
OPA - Enforce whitelisted workload only

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6993]
**User Story**
As an kkp operator, I want to only whitelisted content to be executed on my platform, so that I can assure that no malicious applications are executed on my platform. 

**Acceptance criteria**
- Prerequisite is a CI/CD system and a container registry 
- The whitelist should be a result of the container registry process 
- Everything that has been added to the registry is whitelisted workload
- Everything else is prevented from execution

**Comment by lsviben** [comment]
Hi @shaase-ctrl ,

I investigated a bit both OPA and Harbor and discussed with @rastislavs on how we can proceed here and we see a few options. 

**1. OPA Constraint Template + Constraint Tutorial**
This is the simplest version and it fulfills all the points in the description. We provide a tutorial on our docs on how to create a Constraint Template and Constraint for whitelisting. 

The CT would be in the lines of this, but with parametrized registry image list in the Constraint:
```
package kubernetes.admission                                              

deny[msg] {                                                                
  input.request.kind.kind == "Pod"                                        
  image := input.request.object.spec.containers[_].image                   
  not startswith(image, "hooli.com/")                                       
  msg := sprintf("image '%v' comes from untrusted registry", [image])       
}
```

This would allow users just to add a list of their whitelisted registries to the Constraint. With default Constraints and filtering, they can easily manage the whitelisting across clusters.

On the other hand, this does not include integration with any registry provider. 

**2. Integrate whitelisting with a Harbor registry**

This would be a separate feature where we give the option for users to "Add whitelisted registry" on the Cluster or Admin scope.

We would need to get their Harbor URL and a token from a Harbor Robot account that they prepare with a "Pull Artifacts" permission. We store this in a custom CRD we create for this purpose, and through a controller create the OPA Constraint Template and Constraint like above. 

UI needs to add a dialogue for that in the  Cluster and Admin view. 
If its in the Admin view, we create a Default Constraint so it gets propagated to all user clusters, if its in Cluster view, we just create a Constraint there. 

The solution is basically no 1, with some additional user-friendliness. We are restricted to Harbor ate the beginning but we can add more provider handling in the controller and the "WhitelistedRegistry" CRD.

**3. Deep integration with Harbor**

An idea that came from @rastislavs , this option would include some more integration then what is just in the acceptance criteria, and is a much bigger feature. 

It would include deploying an Harbor instance on the Seed cluster, which would be replicating the artifacts from the users company registry (can be harbor or non-harbor). This way the users would get a "local" image registry. If present, we can set the whitelisting to use only images from our harbor registry. 

As resources deployed on user clusters would need have images from the Seed registry, we would need to mutate them through a mutating webhook so that the registry points to the seed registry. In this case OPA is not really needed as the mutations take care of images with notwhitelisted registries, but it can show violations on the resources that were created before. 

This third option is needs some more brainstorming but that's a starting idea.
