### ISSUE TITLE
HA options for MLA components in User Cluster

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/kubermatic#7207]
Investigate HA options to run protmail and prometheus in User Cluster for MLA.
Ref: https://cortexmetrics.io/docs/guides/ha-pair-handling/
https://grafana.com/docs/loki/latest/clients/promtail/troubleshooting/#log-entries-pushed-after-a-promtail-crash--panic--abruptly-termination
https://grafana.com/docs/loki/latest/clients/promtail/pipelines/

**Comment by SimonTheLeg** [comment]
Regarding HA Promtail:

Short Recap: The original idea of making Promtail highly available is not scaling up the instances (which is also not possible, as it is a Daemonset), but making sure that in case of a loss it recovers the data again. Additionally, it needs to be ensured that there is no duplicate data being pushed. The second part can become quite tricky as Promtail by default generates its own timestamps when reading the loglines and then pushes these to Loki. That is normally very convenient, but in case of an abrupt failure, Promtail might re-assign a later timestamp to an already submitted log line, thus duplicating the data.

The option recommended in the docs is to REGEX-parse the timestamps from the log itself using [timestamp pipelines](https://grafana.com/docs/loki/latest/clients/promtail/pipelines/). However there is one major challenge that every component has a slightly different way of logging. For example prometheus logs in a RFC 3339 and ISO 8601 compatible timestamp prefixed by `ts=` while canal prints the timestamp in only RFC 3339 compatible format without any prefixes. Additionally you have to account for timezone offsets as well.

```sh
# prometheus
ts=2021-11-11T16:43:18.300Z caller=dedupe.go:112 component=remote level=error
# canal
2021-11-11 16:44:12.038 [INFO][61]
```



From my perspective, I can only see two options, both of which are rather complicated:
1. We build our own Promtail Parser for every component we own and then build a catch-all parser for customer-components. For every component a custom REGEX as well as timezone offsetter would be needed
	  + rather straightforward to do
	  - quite a bit of manual effort
	  - effort needs to be done for every new component
	  - if component changes their log-style, we would need to upgrade it as-well
	  - would only work for Kubermatic-owned pods

2. We build a timestamp discoverer into our controller. Basically would read a sample log line to determine the timestamp REGEX and offset and then update the promtail config with it
	  -- extremely complicated to build
	  + would automatically include new components
	  + would work for all pods (as long as the timestamp can be discovered)
	  + could become an open-source contribution to Promtail down the road


Given the complexity and disadvantages of both options, I personally think neither of them it is worth the effort. Because we also have to keep in mind, the worst thing that can happen with the current set-up is a duplication of some logs.

What do you guys think?

**Comment by rastislavs** [comment]
Agree, probably not worth the effort.

**Comment by jiachengxu** [comment]
@SimonTheLeg Thanks for investigating this issue and providing detailed pros and cons for different approaches.
I fully agree with you that it is not worth implementing either approach, and I think we can tolerate slight duplicated logs in case of abrupt failure.

**Comment by SimonTheLeg** [comment]
Okay then I would close the issue, as the Prometheus part is fully done and merged.
