### ISSUE TITLE
Remove hard coded container image references

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#7272]
As reported, if you follow the offline guide,  https://docs.kubermatic.com/kubermatic/v2.17/guides/installation/offline_mode, some of the KKP used  images, seems still to be hard coded and couldn't get overwritten by the `KubermaticConfiguration` object or any other provided option to pull it from a private registry. 
Current Config: https://github.com/kubermatic/kubermatic/blob/master/docs/zz_generated.kubermaticConfiguration.yaml

E.g. the seed-proxy image is fixed: https://github.com/kubermatic/kubermatic/blob/07fa354e9724ef3ea19c0bba983926c41efadf7c/pkg/controller/master-controller-manager/seed-proxy/resources.go#L231

Todos:
- [ ] remove all fixed external image registry dependencies, so the image loader tool + the documented config option can be used to setup a offline setup

**Comment by shaase-ctrl** [comment]
But now the triggered the next bug: In our KubermaticConfiguration we set
userCluster:
    overwriteRegistry: our-private-registry.de
We also set the imagePullSecret for this registry in the config. When creating a user cluster, all images get pulled from the registry with the secret, it seems only kubernetes-dashboard Pods does not have the imagePullSecret set, so pulling of the dashboard fails. All other pods have this setting.

**Comment by maciaszczykm** [comment]
I'm adding SIG UI to take a look on it.

**Comment by maciaszczykm** [comment]
I'm adding @kubermatic/sig-ui  and @kubermatic/sig-api to take a look on it.

**Comment by toschneck** [comment]
@maciaszczykm I created a separate tracking issue for this bug #7274, please same prio as this one

**Comment by dermorz** [comment]
Currently for many components there is an explicit configuration value `dockerRepository` that defines where the images for these are located. These repositories can be overridden in the `KubermaticConfiguration`, but this is required for every single one of them.

If on an air-gapped system all required images get mirrored in a local registry, the registry part of these image locations would all be the same.

```
spec:
  masterController:
    dockerRepository: 172.20.0.2:5000/kubermatic/kubermatic
  seedController:
    dockerRepository: 172.20.0.2:5000/kubermatic/kubermatic
  ui:
    dockerRepository: 172.20.0.2:5000/kubermatic/dashboard
  # etc.
```

Regarding the example from this specific issue, there is currently no config field to rewrite the `dockerRepository` for our `kubermatic/util` image which is used in the seed-proxy controller. A quick-fix would be to make this repository location configurable, but this feels very isolated and does not fix all the other hard-coded images that most probably exist.

Wouldn't it make sense to have an optional global configuration value `overwriteRegistry` that affects all master, seed and user clusters like the one we have for user clusters?

The current mechanism in user cluster components is on manifest creation directly and requires the developer to wrap the registry part of used images. We have functions for that in Go code and also indirectly for yaml manifests (through Go templating).

Adding the possibility to rewrite registries is a manual process on every resource and it is easy to forget during development - as we have noticed previously. So if we want to introduce a global `overwriteRegistry` value to the configuaration, we would also want to make sure this value is respected by every single Pod of created Deployments or DaemonSets.

This could be managed by creating a validating admission webhook which could deny the creation of any resource containing a pod spec with images pulled from a registry other than the defined global config value. Getting an error here would be totally fine because it would point out a bug. The initialization of these pods would fail anyways on air-gapped systems if the image location is not the local registry override. An integration test with this override value set would then fail if any new component is developed where the override mechanism was forgotten.

--- 

Further down the road: When thinking webhooks for pod spec admission it might also be possible to create a mutating admission webhook that actively replaces the image location with the set override value. But this might get a bit complicated because we would want to avoid races between the controllers creating the resources and the webhooks mutating them. This might be possible with some label juggling and smart filtering, but this has to be explored further.
