### ISSUE TITLE
Minio HA setup

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#7334]
As our MLA solutions rely on minio object store, we should make our minio deployment highly available.

**Comment by toschneck** [comment]
@PhillipAmend created a POC with Minio HA Operator, what can be shared and included in the core product charts

**Comment by toschneck** [comment]
@mfahlandt FYI

**Comment by toschneck** [comment]
will get developed from PS team

**Comment by dharapvj** [comment]
While Minio HA is a great. It also comes with its own set of constraints.
1. Minio HA needs to get deployed via Minio Operator. It enforces usage of erasure codes due to which we need, at least, double the storage requirement as current minio as the erasure codes build the redundancy within minio storage itself. [Ref](https://github.com/minio/operator/issues/768)
2. Minio Operator / operator helm chart does not create ingresses for each minio tenant automatically. [Ref](https://github.com/minio/operator/issues/585)
3. Since kkp v2.18, we expect minio to be running on HTTPS for new etcd backup cronjobs - this means we must create additional set of certificates for each of the minio using cert-manager (which again minio operator helm chart does not generate automatically)
4. When we want to use signed urls, the external domain name created via Ingress is does not visible. For this, minio expects special environment variables like MINIO_SERVER_URL. But due to it's design choice, this env var cannot be passed from helm chart like other env vars. So we must create additional secrets containing these variables See [#790](https://github.com/minio/operator/issues/790#issuecomment-917476406)

I had explained above points to @wurbanski earlier in a call.

Due to above points - I do not find Minio HA to be suitable for general purpose replacement of existing Minio solution.

I would rather propose that we should look at utilizing cloud native solutions for public clouds like s3 / azure blob and google cloud blob respectively and fall back to regular minio - wherever required.

CC: @rastislavs @toschneck @wurbanski 

So my suggestion here would be to close this ticket and open another ticket to support cloud native storage

**Comment by dharapvj** [comment]
@mfahlandt - I recommend to not implement this for the [reasons stated above](https://github.com/kubermatic/kubermatic/issues/7334#issuecomment-1049491360)... 

So. I would say that we should close this ticket.

Your opinion?

**Comment by mfahlandt** [comment]
Agreed
