### ISSUE TITLE
Upgrade user cluster MLA backend components

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#7887]
Upgrade the user cluster [MLA backend components](https://github.com/kubermatic/mla/tree/main/charts) running in seed:
- Cortex
- Loki
- Grafana
- Minio

to a newer version. The upgrade process from the previous versions should be straightforward and documented.

**Comment by jiachengxu** [comment]
The following components are upgraded:
- coretex: https://github.com/kubermatic/mla/pull/69
- loki: https://github.com/kubermatic/mla/pull/68
- grafana: https://github.com/kubermatic/mla/pull/67
For minio, since upstream already archived the helm chart, we are already using the latest version of the chart.
/close
