### ISSUE TITLE
Test upgrade of Canal 3.8 to Canal 3.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#7920]
KKP now only supports Canal versions 3.8 (Flannel v0.11.0 + Calico v3.8.0) 3.19 (Flannel v0.13.0 + Calico v3.19.1).
Test how the upgrade between the two works, what are the necessary steps and implications.

**Comment by rastislavs** [comment]
Tests performed before and after upgrade:
- Netperf
- `sonobuoy run --skip-preflight --wait --e2e-focus=Network`

Tests performed during the upgrade:
- nginx deployment exposed via a LoadBalancer service periodically accessed from outside of the cluster (1 sec interval)

Results:
- Netperf tests working fine after upgrade
- E2e conformance tests - same results as before upgrade
- No lost client -> web server connection attempt

Machine deployment rolling restart still recommended - because of MTU handling changes between the CNI versions.
