### ISSUE TITLE
Changelog automation

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#8474]
**User Story**
At the moment we are creating release changelog by manually traversing git history and extracting bits for changelog, this is unsustainable and error prone (history show that sometimes we miss some changes). Changelog generator automation should fix this.

There are few options to consider:
* Require every PR to have a changelog entry, 1 line (like prometheus do)
* Start using kubernetes tools to generate changelog, fetch PRs in between of releases, parse descriptions (like kubernetes do)
* Parse git commits and generate changelog based on that (like controller-runtime do).

**Acceptance criteria**
Release Changelog is generated automatically

**Comment by xmudrii** [comment]
I've researched a bit about this last week. In order to use any automation to generate the changelog, we need to categorize PRs (i.e. have a way to determine what PR is adding a new feature, what's a bug fix, what's a breaking change, etc.). Without categorizing, we need to manually edit the changelog after generating it, which is error-prone and can cause that some changes are lost.

The tool we use right now ([`gchl`](https://github.com/kubermatic/gchl)) supports this by adding type to the `release-note` block: https://github.com/kubermatic/gchl#get-release-notes-via-pr-message-annotation. However, this is not discoverable, searchable, and enforceable, so we should consider using labels instead.

The Kubernetes release-notes tool uses the `release-note` block which we already have, and it supports parsing `kind` labels, which seems like a good enough approach. We can also configure Prow to enforce `kind` labels on all PRs. I think going with this approach makes sense, but we need to bring it up for a broader discussion. It would be nice if we can start enforcing `kind` labels once KKP 2.20 release cycle starts.

**Comment by kron4eg** [comment]
kind label sounds very good

**Comment by xmudrii** [comment]
This has been fixed.

**Comment by xmudrii** [comment]
Wrong repo, I though this is a KubeOne ticket.
/reopen

**Comment by xmudrii** [comment]
We already use gchl for KKP and k-sigs release-notes for KubeOne, so I think we can consider this as done.
/close
