### ISSUE TITLE
Investigate long KubeVirt CCM node initialization

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#8492]
Currently it takes around ~7 minutes to initalize a new node by KubeVirt Cloud Controller Manager (node has a ready state but there is a `node.cloudprovider.kubernetes.io/uninitialized=true` taint`.

Our fork of KubeVirt CCM https://github.com/kubermatic/cloud-provider-kubevirt/ (CCM based on https://github.com/kubernetes/cloud-provider)
The image repo: quay.io/kubermatic/kubevirt-cloud-controller-manager

Suggestion here is to study the cloud provider code and find out if we can do something to speed up the initialization.

Acceptance criteria:
* find out if we can speed up the process (if we cannot then document why)
* create an issue to implement the fix

**Comment by sankalp-r** [comment]
My observation on this issue:

- If the KV infra cluster doesn't have many VMs running, new user-cluster creation(including node initialization with ready-state) takes 3-4 minutes.
- But if the infra cluster has many VMs already running, and we create a new user-cluster, then new VMs for this user-cluster might not be created because of resource crunch.

**Comment by mfranczy** [comment]
After implementing `InstancesV2` from cloud provider pkg the node initalization is much faster.
