### ISSUE TITLE
Metering-Report Download in Dashboard broken

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#8707]
### What happened?

I tried to download the metering report for my KKP setup. But the link lead me to `http://minio.minio.svc.cluster.local:9000/kkp-metering/report-WEEKLY-kubermatic-2022-01-03T00%3A00%3A00Z-2022-01-10T00%3A00%3A00Z.csv?X-Amz-Algorithm=......`

### What should happen?

The link should lead to something I can access from outside the Kubernetes cluster (i.e. via the dashboard).

### How to reproduce?

* Login to the QA environment.
* Be administrator!
* Open admin menu, navigate to "Metering"
* Try to download any of the reports.

### Environment

- KKP Version: 2.19 alphha.4
- Shared or separate master/seed clusters?: yes
- Master/seed cluster provider: AWS

**Comment by xrstf** [comment]
xref kubermatic/kubermatic#8594

**Comment by vgramer** [comment]
I didn't configure the metering credentials correctly. I have used a bucket in minio and setup s3 to the minio clusterIP service. it works for upload but not for download.

I reconfigure the credentials to use an Amazon s3 bucket and it download works. First report is empty because data collection starts a day after.

```
$ aws s3api list-objects --bucket kkp19-metering --query 'Contents[].{Key: Key, Size: Size}'
[
    {
        "Key": "metering-kubermatic-2022-01-11T13:40:58Z.csv",
        "Size": 4733310
    },
    {
        "Key": "report-WEEKLY-kubermatic-2022-01-03T00:00:00Z-2022-01-10T00:00:00Z.csv",
        "Size": 208
    }
]
```
