### ISSUE TITLE
Add Tags to VSphere Machines that are created

### ISSUE THREAD

**Issue by mfahlandt** [kubermatic/kubermatic#8935]
### What would you like to be added? / User Story

Please add the ability to add Tags to machines that are being created in VSphere. 
With this it would set a standard in KKP to be able to set custom tags to different providers. This is important for different users as they have then the ability to use this tags for billing or to cluster machines for their reporting or to enforce rules by tag to KKP machines.

### Acceptance criteria

Add the ability to add a tag in the cluster creation UI & API like we do for example in Azure

![image](https://user-images.githubusercontent.com/5739844/153215604-fa92ce43-0e19-4e92-8755-086b5fa5632c.png)

For the API in the machinedeployment Endpoint e.g

```
 "vsphere": {
          "cpus": 0,
          "diskSizeGB": 0,
          "memory": 0,
          "template": "string"
        }
          "tags": {
            "additionalProp1": "string",
            "additionalProp2": "string",
            "additionalProp3": "string"
          },
         }
```

**Comment by shaase-ctrl** [comment]
Is there a reason we do not have tags consistently in every cloud provider?

**Comment by moadqassem** [comment]
@imharshita 
So in order to achieve this, we need to take care of these points: 

- A default category has to be created arbitrarily for each user cluster, to group related tags together and those tags are probably grouped by the cluster resource(at least from KKP point of view) 
- When a machine deployment is created, there should be a new field called `Tag Category` next each provider tag fields to define the association between tags and categories 
- If there is no category chosen the default category will be used. 
- To assign tags to custom categories(other than the default) users should create them beforehand as KKP won't create other than the default one. 
- Making sure that, KKP has the right credentials to create categories, tags and association. 

Those are the main points that we need to cover. 
cc @mfahlandt
