### ISSUE TITLE
Flatcar update operator should be removed if no flatcar nodes exist - Test Release 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#9068]
# Instructions

- Create cluster on AWS 
- Select any OS EXCEPT flatcar
- Ensure that the cluster is up and healthy
- Create a `MachineDeployment` with flatcar as OS
- Ensure that the machine is up
- Ensure that `flatcar-linux-update-operator` is deployed and scheduled on the flatcar nodes.
- Delete the `MachineDeployment`
- Ensure that `flatcar-linux-update-operator` is removed

# References

xref:
* #8708
* #9170

**Comment by kron4eg** [comment]
:-1: This is broken, machineDeployment can't be delete because flatcar pod constantly respawning on the cordoned Node that's being evicted (so the eviction is happening in endless cycle). It happens beucase `flatcar-linux-update-operator` probably has too much of tolerations that allow it to tolerate `SchedulingDisabled`.

**Comment by kron4eg** [comment]
:heavy_check_mark: with cherrypick works as expected
