### ISSUE TITLE
User-cluster MLA related improvements

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#9346]
Various improvements to User-Cluster MLA feature as discussed with Dev team based on real world usage experience:

**Comment by toschneck** [comment]
@csengerszabo not allowed to add the issues to the epic

**Comment by csengerszabo** [comment]
@toschneck I have added these issues

**Comment by dharapvj** [comment]
For current customer below are crucial..
Kubermatic https://github.com/kubermatic/kubermatic/issues/8506
MLA https://github.com/kubermatic/mla/issues/83

**Comment by almereyda** [comment]
It appears all upstream tickets are resolved.

Therefore this one is resolved, too?

**Comment by dharapvj** [comment]
@almereyda - yes I believe so.

Changes are also available in latest released version(s) of MLA. Pick right version based on your k8s and kkp version.

**Comment by dharapvj** [comment]
@wurbanski - ok to close?

**Comment by wurbanski** [comment]
all good, let's have it closed. Thanks! :)

**Comment by almereyda** [comment]
Thanks! One last thing:

> Pick right version based on your k8s and kkp version.

Do you maintain a version compatibility matrix for the MLA?

Like on:

- https://docs.kubermatic.com/kubermatic/v2.20/architecture/support_policy/supported_versions/

I'm also always wondering about the relation between the `monitoring` chart and the `mla` repository, esp. since the first is present in both KubeOne and Kubermatic. Right now I'm just installing all of this, but maybe I don't need to?

- https://docs.kubermatic.com/kubermatic/v2.20/architecture/support_policy/kkp_components_versioning/
  - (Talking about matrices: https://docs.kubermatic.com/kubermatic/v2.20/architecture/support_policy/os_support_matrix/ isn't one, but the above is. That's another documentation issue, I suppose?)

This (manually generated) list suggests that the `monitoring` components of KKP are an integral part of it.

We're already having a hard time in https://github.com/kubermatic/dashboard/issues/4737 understanding each other's perception about a useful modularity of the documentation components, which may very well reflect intrinsic contradictions within the parts they describe, too. There, MLA is arguably a core component of a working *Installation*.
