### ISSUE TITLE
Add dual-stack support to KKP UI Network Configuration

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9349]
The main aim of this task is to add dual-stack support to KKP UI Network Configuration. Apart from that, it also aims to enhance the Network Configuration UI experience in general.

Basic KKP users may not care about all networking details, so these can be hidden in the UI by default. The only options visible by default should be the CNI + CNI version and (the new) "IPv4" vs. "Dual Stack" option:

![image.png](https://images.zenhubusercontent.com/5f9feacdd87c6f0418bee1e8/b3069a59-3e05-4dc8-ad88-bc0deaade1e8)

When user clicks on "Additional Network Configuration", more configuration options should be available. As an enhancement to the current state, they should all be pre-populated with the default values, so that users would know what exactly will be applied in their cluster:

![Screenshot 2022-04-13 at 16.41.32.png](https://images.zenhubusercontent.com/5f9feacdd87c6f0418bee1e8/e267b5e8-1744-4e6c-a5ec-bf2286c5cd80)

(“Node CIDR Mask Size” and “Node Local DNS Cache” are new config options not yet available in the UI, these should be added as well)

When "Dual Stack" option is selected, some of the configuration options needs to be duplicated for each address family (IPv4 + IPv6), as shown below:

![image.png](https://images.zenhubusercontent.com/5f9feacdd87c6f0418bee1e8/ccfc9406-b137-462b-bc28-2591b06c7925)

Multiple PODs CIDR & Services CIDR, IPv4 & IPv6 Node CIDR Mask Size and Multiple Allowed IP Ranges for NodePorts can be already configured via cluster API of KKP.

API endpoints for loading default values for given cloud provider and CNI will be added as part of https://github.com/kubermatic/kubermatic/issues/9348

**Comment by cschieder** [comment]
Good draft, really like the simplification and prefilling, minor tweaks:
- I think we can say `Dual Stack (IPv4 and IPv6)` or `IPv4 and IPv6 (Dual Stack)` in the radio button to make it clearer
- in the dual stack additional settings let's add a little headline, `IPv4` and `IPv6` respectively so it's immediately apparent that these are the settings for each and you can change them separately
- instead of "additional" we should probably say "advanced" as the settings are not optional add ons but an elaboration/advanced setting of the radio button options

**Comment by rastislavs** [comment]
@cschieder yeah, I like all tweaks that you proposed. On `Dual Stack (IPv4 and IPv6)` or `IPv4 and IPv6 (Dual Stack)`, I cannot really decide which one is better :)

**Comment by shaase-ctrl** [comment]
` IPv4 and IPv6 (Dual Stack) ` is the better option, as Dual Stack is already a term known to fewer people.
