### ISSUE TITLE
Add-on controller

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#95]
Deploy k8s add-on on the customer clusters e.g. kube-dns, monitoring, logging 

For this we need to extend the api server. The api server should create a third party resource. 

The Add-on controller deploy the application based on the third party resource.

**Comment by scheeles** [comment]
Use as endpoint `/api/v1/dc/{dc}/cluster/{cluster}/addon`

**Comment by mrIncompetent** [comment]
As discussed we might do the controller-part with https://github.com/kubernetes/helm

Helm does contain out of 2 components: Server (installs packages) and Client (Cli)
The server normally runs on the cluster where the packages (called charts) should be installed.

We should check if it is easily possible to integrate Helm and modify it so we only have one server which runs on our cluster instead of having a server on each customer cluster

**Comment by scruplelesswizard** [comment]
@mrIncompetent what is the status on this?

**Comment by mrIncompetent** [comment]
Its ready to merge :)
