### ISSUE TITLE
CCM readiness of Azure

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#9919]

**Comment by embik** [comment]
Notes on Azure CCM/CSI readiness:

- KubeOne has been running Azure CCM and CSI drivers successfully for quite some time.
- CSI migration is supported by Kubernetes via `CSIMigrationAzureDisk` (beta since 1.19, enabled by default since 1.23, GA since 1.24) and `CSIMigrationAzureFile` (beta since 1.21, enabled by default since 1.24).
- Azure CCM has frequent releases and stays up to date with upstream versions (https://github.com/kubernetes-sigs/cloud-provider-azure/releases).

**Comment by embik** [comment]
I raised #9957 for this. Closing this "exploration" ticket.
